
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `NextBestAction` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model NextBestAction
 * 
 */
export type NextBestActionModel = runtime.Types.Result.DefaultSelection<Prisma.$NextBestActionPayload>

export type AggregateNextBestAction = {
  _count: NextBestActionCountAggregateOutputType | null
  _avg: NextBestActionAvgAggregateOutputType | null
  _sum: NextBestActionSumAggregateOutputType | null
  _min: NextBestActionMinAggregateOutputType | null
  _max: NextBestActionMaxAggregateOutputType | null
}

export type NextBestActionAvgAggregateOutputType = {
  confidence: runtime.Decimal | null
}

export type NextBestActionSumAggregateOutputType = {
  confidence: runtime.Decimal | null
}

export type NextBestActionMinAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  journeyId: string | null
  actionType: $Enums.CommercialActionType | null
  title: string | null
  description: string | null
  reason: string | null
  confidence: runtime.Decimal | null
  priority: $Enums.NextBestActionPriority | null
  source: $Enums.NextBestActionSource | null
  expiresAt: Date | null
  acceptedAt: Date | null
  rejectedAt: Date | null
  executedActionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NextBestActionMaxAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  journeyId: string | null
  actionType: $Enums.CommercialActionType | null
  title: string | null
  description: string | null
  reason: string | null
  confidence: runtime.Decimal | null
  priority: $Enums.NextBestActionPriority | null
  source: $Enums.NextBestActionSource | null
  expiresAt: Date | null
  acceptedAt: Date | null
  rejectedAt: Date | null
  executedActionId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type NextBestActionCountAggregateOutputType = {
  id: number
  workspaceId: number
  journeyId: number
  actionType: number
  title: number
  description: number
  reason: number
  confidence: number
  priority: number
  source: number
  expiresAt: number
  acceptedAt: number
  rejectedAt: number
  executedActionId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type NextBestActionAvgAggregateInputType = {
  confidence?: true
}

export type NextBestActionSumAggregateInputType = {
  confidence?: true
}

export type NextBestActionMinAggregateInputType = {
  id?: true
  workspaceId?: true
  journeyId?: true
  actionType?: true
  title?: true
  description?: true
  reason?: true
  confidence?: true
  priority?: true
  source?: true
  expiresAt?: true
  acceptedAt?: true
  rejectedAt?: true
  executedActionId?: true
  createdAt?: true
  updatedAt?: true
}

export type NextBestActionMaxAggregateInputType = {
  id?: true
  workspaceId?: true
  journeyId?: true
  actionType?: true
  title?: true
  description?: true
  reason?: true
  confidence?: true
  priority?: true
  source?: true
  expiresAt?: true
  acceptedAt?: true
  rejectedAt?: true
  executedActionId?: true
  createdAt?: true
  updatedAt?: true
}

export type NextBestActionCountAggregateInputType = {
  id?: true
  workspaceId?: true
  journeyId?: true
  actionType?: true
  title?: true
  description?: true
  reason?: true
  confidence?: true
  priority?: true
  source?: true
  expiresAt?: true
  acceptedAt?: true
  rejectedAt?: true
  executedActionId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type NextBestActionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NextBestAction to aggregate.
   */
  where?: Prisma.NextBestActionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NextBestActions to fetch.
   */
  orderBy?: Prisma.NextBestActionOrderByWithRelationInput | Prisma.NextBestActionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.NextBestActionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NextBestActions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NextBestActions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned NextBestActions
  **/
  _count?: true | NextBestActionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: NextBestActionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: NextBestActionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: NextBestActionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: NextBestActionMaxAggregateInputType
}

export type GetNextBestActionAggregateType<T extends NextBestActionAggregateArgs> = {
      [P in keyof T & keyof AggregateNextBestAction]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateNextBestAction[P]>
    : Prisma.GetScalarType<T[P], AggregateNextBestAction[P]>
}




export type NextBestActionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.NextBestActionWhereInput
  orderBy?: Prisma.NextBestActionOrderByWithAggregationInput | Prisma.NextBestActionOrderByWithAggregationInput[]
  by: Prisma.NextBestActionScalarFieldEnum[] | Prisma.NextBestActionScalarFieldEnum
  having?: Prisma.NextBestActionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: NextBestActionCountAggregateInputType | true
  _avg?: NextBestActionAvgAggregateInputType
  _sum?: NextBestActionSumAggregateInputType
  _min?: NextBestActionMinAggregateInputType
  _max?: NextBestActionMaxAggregateInputType
}

export type NextBestActionGroupByOutputType = {
  id: string
  workspaceId: string
  journeyId: string
  actionType: $Enums.CommercialActionType
  title: string
  description: string | null
  reason: string
  confidence: runtime.Decimal
  priority: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt: Date | null
  acceptedAt: Date | null
  rejectedAt: Date | null
  executedActionId: string | null
  createdAt: Date
  updatedAt: Date
  _count: NextBestActionCountAggregateOutputType | null
  _avg: NextBestActionAvgAggregateOutputType | null
  _sum: NextBestActionSumAggregateOutputType | null
  _min: NextBestActionMinAggregateOutputType | null
  _max: NextBestActionMaxAggregateOutputType | null
}

export type GetNextBestActionGroupByPayload<T extends NextBestActionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<NextBestActionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof NextBestActionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], NextBestActionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], NextBestActionGroupByOutputType[P]>
      }
    >
  >



export type NextBestActionWhereInput = {
  AND?: Prisma.NextBestActionWhereInput | Prisma.NextBestActionWhereInput[]
  OR?: Prisma.NextBestActionWhereInput[]
  NOT?: Prisma.NextBestActionWhereInput | Prisma.NextBestActionWhereInput[]
  id?: Prisma.StringFilter<"NextBestAction"> | string
  workspaceId?: Prisma.StringFilter<"NextBestAction"> | string
  journeyId?: Prisma.StringFilter<"NextBestAction"> | string
  actionType?: Prisma.EnumCommercialActionTypeFilter<"NextBestAction"> | $Enums.CommercialActionType
  title?: Prisma.StringFilter<"NextBestAction"> | string
  description?: Prisma.StringNullableFilter<"NextBestAction"> | string | null
  reason?: Prisma.StringFilter<"NextBestAction"> | string
  confidence?: Prisma.DecimalFilter<"NextBestAction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFilter<"NextBestAction"> | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFilter<"NextBestAction"> | $Enums.NextBestActionSource
  expiresAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  acceptedAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  rejectedAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  executedActionId?: Prisma.StringNullableFilter<"NextBestAction"> | string | null
  createdAt?: Prisma.DateTimeFilter<"NextBestAction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NextBestAction"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  journey?: Prisma.XOR<Prisma.CommercialJourneyScalarRelationFilter, Prisma.CommercialJourneyWhereInput>
  executedAction?: Prisma.XOR<Prisma.CommercialActionNullableScalarRelationFilter, Prisma.CommercialActionWhereInput> | null
}

export type NextBestActionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  reason?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  source?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  acceptedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  rejectedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  executedActionId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
  journey?: Prisma.CommercialJourneyOrderByWithRelationInput
  executedAction?: Prisma.CommercialActionOrderByWithRelationInput
}

export type NextBestActionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  executedActionId?: string
  AND?: Prisma.NextBestActionWhereInput | Prisma.NextBestActionWhereInput[]
  OR?: Prisma.NextBestActionWhereInput[]
  NOT?: Prisma.NextBestActionWhereInput | Prisma.NextBestActionWhereInput[]
  workspaceId?: Prisma.StringFilter<"NextBestAction"> | string
  journeyId?: Prisma.StringFilter<"NextBestAction"> | string
  actionType?: Prisma.EnumCommercialActionTypeFilter<"NextBestAction"> | $Enums.CommercialActionType
  title?: Prisma.StringFilter<"NextBestAction"> | string
  description?: Prisma.StringNullableFilter<"NextBestAction"> | string | null
  reason?: Prisma.StringFilter<"NextBestAction"> | string
  confidence?: Prisma.DecimalFilter<"NextBestAction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFilter<"NextBestAction"> | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFilter<"NextBestAction"> | $Enums.NextBestActionSource
  expiresAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  acceptedAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  rejectedAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"NextBestAction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NextBestAction"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  journey?: Prisma.XOR<Prisma.CommercialJourneyScalarRelationFilter, Prisma.CommercialJourneyWhereInput>
  executedAction?: Prisma.XOR<Prisma.CommercialActionNullableScalarRelationFilter, Prisma.CommercialActionWhereInput> | null
}, "id" | "executedActionId">

export type NextBestActionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  reason?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  source?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  acceptedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  rejectedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  executedActionId?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.NextBestActionCountOrderByAggregateInput
  _avg?: Prisma.NextBestActionAvgOrderByAggregateInput
  _max?: Prisma.NextBestActionMaxOrderByAggregateInput
  _min?: Prisma.NextBestActionMinOrderByAggregateInput
  _sum?: Prisma.NextBestActionSumOrderByAggregateInput
}

export type NextBestActionScalarWhereWithAggregatesInput = {
  AND?: Prisma.NextBestActionScalarWhereWithAggregatesInput | Prisma.NextBestActionScalarWhereWithAggregatesInput[]
  OR?: Prisma.NextBestActionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.NextBestActionScalarWhereWithAggregatesInput | Prisma.NextBestActionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"NextBestAction"> | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"NextBestAction"> | string
  journeyId?: Prisma.StringWithAggregatesFilter<"NextBestAction"> | string
  actionType?: Prisma.EnumCommercialActionTypeWithAggregatesFilter<"NextBestAction"> | $Enums.CommercialActionType
  title?: Prisma.StringWithAggregatesFilter<"NextBestAction"> | string
  description?: Prisma.StringNullableWithAggregatesFilter<"NextBestAction"> | string | null
  reason?: Prisma.StringWithAggregatesFilter<"NextBestAction"> | string
  confidence?: Prisma.DecimalWithAggregatesFilter<"NextBestAction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityWithAggregatesFilter<"NextBestAction"> | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceWithAggregatesFilter<"NextBestAction"> | $Enums.NextBestActionSource
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"NextBestAction"> | Date | string | null
  acceptedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"NextBestAction"> | Date | string | null
  rejectedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"NextBestAction"> | Date | string | null
  executedActionId?: Prisma.StringNullableWithAggregatesFilter<"NextBestAction"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"NextBestAction"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"NextBestAction"> | Date | string
}

export type NextBestActionCreateInput = {
  id?: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutNextBestActionsInput
  journey: Prisma.CommercialJourneyCreateNestedOneWithoutNextBestActionsInput
  executedAction?: Prisma.CommercialActionCreateNestedOneWithoutExecutedNextBestActionInput
}

export type NextBestActionUncheckedCreateInput = {
  id?: string
  workspaceId: string
  journeyId: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  executedActionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NextBestActionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutNextBestActionsNestedInput
  journey?: Prisma.CommercialJourneyUpdateOneRequiredWithoutNextBestActionsNestedInput
  executedAction?: Prisma.CommercialActionUpdateOneWithoutExecutedNextBestActionNestedInput
}

export type NextBestActionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  executedActionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NextBestActionCreateManyInput = {
  id?: string
  workspaceId: string
  journeyId: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  executedActionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NextBestActionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NextBestActionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  executedActionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NextBestActionListRelationFilter = {
  every?: Prisma.NextBestActionWhereInput
  some?: Prisma.NextBestActionWhereInput
  none?: Prisma.NextBestActionWhereInput
}

export type NextBestActionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type NextBestActionNullableScalarRelationFilter = {
  is?: Prisma.NextBestActionWhereInput | null
  isNot?: Prisma.NextBestActionWhereInput | null
}

export type NextBestActionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  source?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  acceptedAt?: Prisma.SortOrder
  rejectedAt?: Prisma.SortOrder
  executedActionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NextBestActionAvgOrderByAggregateInput = {
  confidence?: Prisma.SortOrder
}

export type NextBestActionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  source?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  acceptedAt?: Prisma.SortOrder
  rejectedAt?: Prisma.SortOrder
  executedActionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NextBestActionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  actionType?: Prisma.SortOrder
  title?: Prisma.SortOrder
  description?: Prisma.SortOrder
  reason?: Prisma.SortOrder
  confidence?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  source?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  acceptedAt?: Prisma.SortOrder
  rejectedAt?: Prisma.SortOrder
  executedActionId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type NextBestActionSumOrderByAggregateInput = {
  confidence?: Prisma.SortOrder
}

export type NextBestActionCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutWorkspaceInput, Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput> | Prisma.NextBestActionCreateWithoutWorkspaceInput[] | Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutWorkspaceInput | Prisma.NextBestActionCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.NextBestActionCreateManyWorkspaceInputEnvelope
  connect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
}

export type NextBestActionUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutWorkspaceInput, Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput> | Prisma.NextBestActionCreateWithoutWorkspaceInput[] | Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutWorkspaceInput | Prisma.NextBestActionCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.NextBestActionCreateManyWorkspaceInputEnvelope
  connect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
}

export type NextBestActionUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutWorkspaceInput, Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput> | Prisma.NextBestActionCreateWithoutWorkspaceInput[] | Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutWorkspaceInput | Prisma.NextBestActionCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.NextBestActionUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.NextBestActionUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.NextBestActionCreateManyWorkspaceInputEnvelope
  set?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  disconnect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  delete?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  connect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  update?: Prisma.NextBestActionUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.NextBestActionUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.NextBestActionUpdateManyWithWhereWithoutWorkspaceInput | Prisma.NextBestActionUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.NextBestActionScalarWhereInput | Prisma.NextBestActionScalarWhereInput[]
}

export type NextBestActionUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutWorkspaceInput, Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput> | Prisma.NextBestActionCreateWithoutWorkspaceInput[] | Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutWorkspaceInput | Prisma.NextBestActionCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.NextBestActionUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.NextBestActionUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.NextBestActionCreateManyWorkspaceInputEnvelope
  set?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  disconnect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  delete?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  connect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  update?: Prisma.NextBestActionUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.NextBestActionUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.NextBestActionUpdateManyWithWhereWithoutWorkspaceInput | Prisma.NextBestActionUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.NextBestActionScalarWhereInput | Prisma.NextBestActionScalarWhereInput[]
}

export type NextBestActionCreateNestedManyWithoutJourneyInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutJourneyInput, Prisma.NextBestActionUncheckedCreateWithoutJourneyInput> | Prisma.NextBestActionCreateWithoutJourneyInput[] | Prisma.NextBestActionUncheckedCreateWithoutJourneyInput[]
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutJourneyInput | Prisma.NextBestActionCreateOrConnectWithoutJourneyInput[]
  createMany?: Prisma.NextBestActionCreateManyJourneyInputEnvelope
  connect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
}

export type NextBestActionUncheckedCreateNestedManyWithoutJourneyInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutJourneyInput, Prisma.NextBestActionUncheckedCreateWithoutJourneyInput> | Prisma.NextBestActionCreateWithoutJourneyInput[] | Prisma.NextBestActionUncheckedCreateWithoutJourneyInput[]
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutJourneyInput | Prisma.NextBestActionCreateOrConnectWithoutJourneyInput[]
  createMany?: Prisma.NextBestActionCreateManyJourneyInputEnvelope
  connect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
}

export type NextBestActionUpdateManyWithoutJourneyNestedInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutJourneyInput, Prisma.NextBestActionUncheckedCreateWithoutJourneyInput> | Prisma.NextBestActionCreateWithoutJourneyInput[] | Prisma.NextBestActionUncheckedCreateWithoutJourneyInput[]
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutJourneyInput | Prisma.NextBestActionCreateOrConnectWithoutJourneyInput[]
  upsert?: Prisma.NextBestActionUpsertWithWhereUniqueWithoutJourneyInput | Prisma.NextBestActionUpsertWithWhereUniqueWithoutJourneyInput[]
  createMany?: Prisma.NextBestActionCreateManyJourneyInputEnvelope
  set?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  disconnect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  delete?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  connect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  update?: Prisma.NextBestActionUpdateWithWhereUniqueWithoutJourneyInput | Prisma.NextBestActionUpdateWithWhereUniqueWithoutJourneyInput[]
  updateMany?: Prisma.NextBestActionUpdateManyWithWhereWithoutJourneyInput | Prisma.NextBestActionUpdateManyWithWhereWithoutJourneyInput[]
  deleteMany?: Prisma.NextBestActionScalarWhereInput | Prisma.NextBestActionScalarWhereInput[]
}

export type NextBestActionUncheckedUpdateManyWithoutJourneyNestedInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutJourneyInput, Prisma.NextBestActionUncheckedCreateWithoutJourneyInput> | Prisma.NextBestActionCreateWithoutJourneyInput[] | Prisma.NextBestActionUncheckedCreateWithoutJourneyInput[]
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutJourneyInput | Prisma.NextBestActionCreateOrConnectWithoutJourneyInput[]
  upsert?: Prisma.NextBestActionUpsertWithWhereUniqueWithoutJourneyInput | Prisma.NextBestActionUpsertWithWhereUniqueWithoutJourneyInput[]
  createMany?: Prisma.NextBestActionCreateManyJourneyInputEnvelope
  set?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  disconnect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  delete?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  connect?: Prisma.NextBestActionWhereUniqueInput | Prisma.NextBestActionWhereUniqueInput[]
  update?: Prisma.NextBestActionUpdateWithWhereUniqueWithoutJourneyInput | Prisma.NextBestActionUpdateWithWhereUniqueWithoutJourneyInput[]
  updateMany?: Prisma.NextBestActionUpdateManyWithWhereWithoutJourneyInput | Prisma.NextBestActionUpdateManyWithWhereWithoutJourneyInput[]
  deleteMany?: Prisma.NextBestActionScalarWhereInput | Prisma.NextBestActionScalarWhereInput[]
}

export type NextBestActionCreateNestedOneWithoutExecutedActionInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutExecutedActionInput, Prisma.NextBestActionUncheckedCreateWithoutExecutedActionInput>
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutExecutedActionInput
  connect?: Prisma.NextBestActionWhereUniqueInput
}

export type NextBestActionUncheckedCreateNestedOneWithoutExecutedActionInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutExecutedActionInput, Prisma.NextBestActionUncheckedCreateWithoutExecutedActionInput>
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutExecutedActionInput
  connect?: Prisma.NextBestActionWhereUniqueInput
}

export type NextBestActionUpdateOneWithoutExecutedActionNestedInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutExecutedActionInput, Prisma.NextBestActionUncheckedCreateWithoutExecutedActionInput>
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutExecutedActionInput
  upsert?: Prisma.NextBestActionUpsertWithoutExecutedActionInput
  disconnect?: Prisma.NextBestActionWhereInput | boolean
  delete?: Prisma.NextBestActionWhereInput | boolean
  connect?: Prisma.NextBestActionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NextBestActionUpdateToOneWithWhereWithoutExecutedActionInput, Prisma.NextBestActionUpdateWithoutExecutedActionInput>, Prisma.NextBestActionUncheckedUpdateWithoutExecutedActionInput>
}

export type NextBestActionUncheckedUpdateOneWithoutExecutedActionNestedInput = {
  create?: Prisma.XOR<Prisma.NextBestActionCreateWithoutExecutedActionInput, Prisma.NextBestActionUncheckedCreateWithoutExecutedActionInput>
  connectOrCreate?: Prisma.NextBestActionCreateOrConnectWithoutExecutedActionInput
  upsert?: Prisma.NextBestActionUpsertWithoutExecutedActionInput
  disconnect?: Prisma.NextBestActionWhereInput | boolean
  delete?: Prisma.NextBestActionWhereInput | boolean
  connect?: Prisma.NextBestActionWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.NextBestActionUpdateToOneWithWhereWithoutExecutedActionInput, Prisma.NextBestActionUpdateWithoutExecutedActionInput>, Prisma.NextBestActionUncheckedUpdateWithoutExecutedActionInput>
}

export type EnumNextBestActionPriorityFieldUpdateOperationsInput = {
  set?: $Enums.NextBestActionPriority
}

export type EnumNextBestActionSourceFieldUpdateOperationsInput = {
  set?: $Enums.NextBestActionSource
}

export type NextBestActionCreateWithoutWorkspaceInput = {
  id?: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  journey: Prisma.CommercialJourneyCreateNestedOneWithoutNextBestActionsInput
  executedAction?: Prisma.CommercialActionCreateNestedOneWithoutExecutedNextBestActionInput
}

export type NextBestActionUncheckedCreateWithoutWorkspaceInput = {
  id?: string
  journeyId: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  executedActionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NextBestActionCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.NextBestActionWhereUniqueInput
  create: Prisma.XOR<Prisma.NextBestActionCreateWithoutWorkspaceInput, Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput>
}

export type NextBestActionCreateManyWorkspaceInputEnvelope = {
  data: Prisma.NextBestActionCreateManyWorkspaceInput | Prisma.NextBestActionCreateManyWorkspaceInput[]
  skipDuplicates?: boolean
}

export type NextBestActionUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.NextBestActionWhereUniqueInput
  update: Prisma.XOR<Prisma.NextBestActionUpdateWithoutWorkspaceInput, Prisma.NextBestActionUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.NextBestActionCreateWithoutWorkspaceInput, Prisma.NextBestActionUncheckedCreateWithoutWorkspaceInput>
}

export type NextBestActionUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.NextBestActionWhereUniqueInput
  data: Prisma.XOR<Prisma.NextBestActionUpdateWithoutWorkspaceInput, Prisma.NextBestActionUncheckedUpdateWithoutWorkspaceInput>
}

export type NextBestActionUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.NextBestActionScalarWhereInput
  data: Prisma.XOR<Prisma.NextBestActionUpdateManyMutationInput, Prisma.NextBestActionUncheckedUpdateManyWithoutWorkspaceInput>
}

export type NextBestActionScalarWhereInput = {
  AND?: Prisma.NextBestActionScalarWhereInput | Prisma.NextBestActionScalarWhereInput[]
  OR?: Prisma.NextBestActionScalarWhereInput[]
  NOT?: Prisma.NextBestActionScalarWhereInput | Prisma.NextBestActionScalarWhereInput[]
  id?: Prisma.StringFilter<"NextBestAction"> | string
  workspaceId?: Prisma.StringFilter<"NextBestAction"> | string
  journeyId?: Prisma.StringFilter<"NextBestAction"> | string
  actionType?: Prisma.EnumCommercialActionTypeFilter<"NextBestAction"> | $Enums.CommercialActionType
  title?: Prisma.StringFilter<"NextBestAction"> | string
  description?: Prisma.StringNullableFilter<"NextBestAction"> | string | null
  reason?: Prisma.StringFilter<"NextBestAction"> | string
  confidence?: Prisma.DecimalFilter<"NextBestAction"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFilter<"NextBestAction"> | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFilter<"NextBestAction"> | $Enums.NextBestActionSource
  expiresAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  acceptedAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  rejectedAt?: Prisma.DateTimeNullableFilter<"NextBestAction"> | Date | string | null
  executedActionId?: Prisma.StringNullableFilter<"NextBestAction"> | string | null
  createdAt?: Prisma.DateTimeFilter<"NextBestAction"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"NextBestAction"> | Date | string
}

export type NextBestActionCreateWithoutJourneyInput = {
  id?: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutNextBestActionsInput
  executedAction?: Prisma.CommercialActionCreateNestedOneWithoutExecutedNextBestActionInput
}

export type NextBestActionUncheckedCreateWithoutJourneyInput = {
  id?: string
  workspaceId: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  executedActionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NextBestActionCreateOrConnectWithoutJourneyInput = {
  where: Prisma.NextBestActionWhereUniqueInput
  create: Prisma.XOR<Prisma.NextBestActionCreateWithoutJourneyInput, Prisma.NextBestActionUncheckedCreateWithoutJourneyInput>
}

export type NextBestActionCreateManyJourneyInputEnvelope = {
  data: Prisma.NextBestActionCreateManyJourneyInput | Prisma.NextBestActionCreateManyJourneyInput[]
  skipDuplicates?: boolean
}

export type NextBestActionUpsertWithWhereUniqueWithoutJourneyInput = {
  where: Prisma.NextBestActionWhereUniqueInput
  update: Prisma.XOR<Prisma.NextBestActionUpdateWithoutJourneyInput, Prisma.NextBestActionUncheckedUpdateWithoutJourneyInput>
  create: Prisma.XOR<Prisma.NextBestActionCreateWithoutJourneyInput, Prisma.NextBestActionUncheckedCreateWithoutJourneyInput>
}

export type NextBestActionUpdateWithWhereUniqueWithoutJourneyInput = {
  where: Prisma.NextBestActionWhereUniqueInput
  data: Prisma.XOR<Prisma.NextBestActionUpdateWithoutJourneyInput, Prisma.NextBestActionUncheckedUpdateWithoutJourneyInput>
}

export type NextBestActionUpdateManyWithWhereWithoutJourneyInput = {
  where: Prisma.NextBestActionScalarWhereInput
  data: Prisma.XOR<Prisma.NextBestActionUpdateManyMutationInput, Prisma.NextBestActionUncheckedUpdateManyWithoutJourneyInput>
}

export type NextBestActionCreateWithoutExecutedActionInput = {
  id?: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutNextBestActionsInput
  journey: Prisma.CommercialJourneyCreateNestedOneWithoutNextBestActionsInput
}

export type NextBestActionUncheckedCreateWithoutExecutedActionInput = {
  id?: string
  workspaceId: string
  journeyId: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NextBestActionCreateOrConnectWithoutExecutedActionInput = {
  where: Prisma.NextBestActionWhereUniqueInput
  create: Prisma.XOR<Prisma.NextBestActionCreateWithoutExecutedActionInput, Prisma.NextBestActionUncheckedCreateWithoutExecutedActionInput>
}

export type NextBestActionUpsertWithoutExecutedActionInput = {
  update: Prisma.XOR<Prisma.NextBestActionUpdateWithoutExecutedActionInput, Prisma.NextBestActionUncheckedUpdateWithoutExecutedActionInput>
  create: Prisma.XOR<Prisma.NextBestActionCreateWithoutExecutedActionInput, Prisma.NextBestActionUncheckedCreateWithoutExecutedActionInput>
  where?: Prisma.NextBestActionWhereInput
}

export type NextBestActionUpdateToOneWithWhereWithoutExecutedActionInput = {
  where?: Prisma.NextBestActionWhereInput
  data: Prisma.XOR<Prisma.NextBestActionUpdateWithoutExecutedActionInput, Prisma.NextBestActionUncheckedUpdateWithoutExecutedActionInput>
}

export type NextBestActionUpdateWithoutExecutedActionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutNextBestActionsNestedInput
  journey?: Prisma.CommercialJourneyUpdateOneRequiredWithoutNextBestActionsNestedInput
}

export type NextBestActionUncheckedUpdateWithoutExecutedActionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NextBestActionCreateManyWorkspaceInput = {
  id?: string
  journeyId: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  executedActionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NextBestActionUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  journey?: Prisma.CommercialJourneyUpdateOneRequiredWithoutNextBestActionsNestedInput
  executedAction?: Prisma.CommercialActionUpdateOneWithoutExecutedNextBestActionNestedInput
}

export type NextBestActionUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  executedActionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NextBestActionUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  executedActionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NextBestActionCreateManyJourneyInput = {
  id?: string
  workspaceId: string
  actionType: $Enums.CommercialActionType
  title: string
  description?: string | null
  reason: string
  confidence: runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: $Enums.NextBestActionPriority
  source: $Enums.NextBestActionSource
  expiresAt?: Date | string | null
  acceptedAt?: Date | string | null
  rejectedAt?: Date | string | null
  executedActionId?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type NextBestActionUpdateWithoutJourneyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutNextBestActionsNestedInput
  executedAction?: Prisma.CommercialActionUpdateOneWithoutExecutedNextBestActionNestedInput
}

export type NextBestActionUncheckedUpdateWithoutJourneyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  executedActionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type NextBestActionUncheckedUpdateManyWithoutJourneyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  actionType?: Prisma.EnumCommercialActionTypeFieldUpdateOperationsInput | $Enums.CommercialActionType
  title?: Prisma.StringFieldUpdateOperationsInput | string
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  reason?: Prisma.StringFieldUpdateOperationsInput | string
  confidence?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  priority?: Prisma.EnumNextBestActionPriorityFieldUpdateOperationsInput | $Enums.NextBestActionPriority
  source?: Prisma.EnumNextBestActionSourceFieldUpdateOperationsInput | $Enums.NextBestActionSource
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  acceptedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  rejectedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  executedActionId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type NextBestActionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  journeyId?: boolean
  actionType?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  confidence?: boolean
  priority?: boolean
  source?: boolean
  expiresAt?: boolean
  acceptedAt?: boolean
  rejectedAt?: boolean
  executedActionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
  executedAction?: boolean | Prisma.NextBestAction$executedActionArgs<ExtArgs>
}, ExtArgs["result"]["nextBestAction"]>

export type NextBestActionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  journeyId?: boolean
  actionType?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  confidence?: boolean
  priority?: boolean
  source?: boolean
  expiresAt?: boolean
  acceptedAt?: boolean
  rejectedAt?: boolean
  executedActionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
  executedAction?: boolean | Prisma.NextBestAction$executedActionArgs<ExtArgs>
}, ExtArgs["result"]["nextBestAction"]>

export type NextBestActionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  journeyId?: boolean
  actionType?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  confidence?: boolean
  priority?: boolean
  source?: boolean
  expiresAt?: boolean
  acceptedAt?: boolean
  rejectedAt?: boolean
  executedActionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
  executedAction?: boolean | Prisma.NextBestAction$executedActionArgs<ExtArgs>
}, ExtArgs["result"]["nextBestAction"]>

export type NextBestActionSelectScalar = {
  id?: boolean
  workspaceId?: boolean
  journeyId?: boolean
  actionType?: boolean
  title?: boolean
  description?: boolean
  reason?: boolean
  confidence?: boolean
  priority?: boolean
  source?: boolean
  expiresAt?: boolean
  acceptedAt?: boolean
  rejectedAt?: boolean
  executedActionId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type NextBestActionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workspaceId" | "journeyId" | "actionType" | "title" | "description" | "reason" | "confidence" | "priority" | "source" | "expiresAt" | "acceptedAt" | "rejectedAt" | "executedActionId" | "createdAt" | "updatedAt", ExtArgs["result"]["nextBestAction"]>
export type NextBestActionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
  executedAction?: boolean | Prisma.NextBestAction$executedActionArgs<ExtArgs>
}
export type NextBestActionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
  executedAction?: boolean | Prisma.NextBestAction$executedActionArgs<ExtArgs>
}
export type NextBestActionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
  executedAction?: boolean | Prisma.NextBestAction$executedActionArgs<ExtArgs>
}

export type $NextBestActionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "NextBestAction"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
    journey: Prisma.$CommercialJourneyPayload<ExtArgs>
    executedAction: Prisma.$CommercialActionPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    workspaceId: string
    journeyId: string
    actionType: $Enums.CommercialActionType
    title: string
    description: string | null
    reason: string
    confidence: runtime.Decimal
    priority: $Enums.NextBestActionPriority
    source: $Enums.NextBestActionSource
    expiresAt: Date | null
    acceptedAt: Date | null
    rejectedAt: Date | null
    executedActionId: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["nextBestAction"]>
  composites: {}
}

export type NextBestActionGetPayload<S extends boolean | null | undefined | NextBestActionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload, S>

export type NextBestActionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<NextBestActionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: NextBestActionCountAggregateInputType | true
  }

export interface NextBestActionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['NextBestAction'], meta: { name: 'NextBestAction' } }
  /**
   * Find zero or one NextBestAction that matches the filter.
   * @param {NextBestActionFindUniqueArgs} args - Arguments to find a NextBestAction
   * @example
   * // Get one NextBestAction
   * const nextBestAction = await prisma.nextBestAction.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends NextBestActionFindUniqueArgs>(args: Prisma.SelectSubset<T, NextBestActionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__NextBestActionClient<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one NextBestAction that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {NextBestActionFindUniqueOrThrowArgs} args - Arguments to find a NextBestAction
   * @example
   * // Get one NextBestAction
   * const nextBestAction = await prisma.nextBestAction.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends NextBestActionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, NextBestActionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__NextBestActionClient<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NextBestAction that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NextBestActionFindFirstArgs} args - Arguments to find a NextBestAction
   * @example
   * // Get one NextBestAction
   * const nextBestAction = await prisma.nextBestAction.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends NextBestActionFindFirstArgs>(args?: Prisma.SelectSubset<T, NextBestActionFindFirstArgs<ExtArgs>>): Prisma.Prisma__NextBestActionClient<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first NextBestAction that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NextBestActionFindFirstOrThrowArgs} args - Arguments to find a NextBestAction
   * @example
   * // Get one NextBestAction
   * const nextBestAction = await prisma.nextBestAction.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends NextBestActionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, NextBestActionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__NextBestActionClient<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more NextBestActions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NextBestActionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all NextBestActions
   * const nextBestActions = await prisma.nextBestAction.findMany()
   * 
   * // Get first 10 NextBestActions
   * const nextBestActions = await prisma.nextBestAction.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const nextBestActionWithIdOnly = await prisma.nextBestAction.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends NextBestActionFindManyArgs>(args?: Prisma.SelectSubset<T, NextBestActionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a NextBestAction.
   * @param {NextBestActionCreateArgs} args - Arguments to create a NextBestAction.
   * @example
   * // Create one NextBestAction
   * const NextBestAction = await prisma.nextBestAction.create({
   *   data: {
   *     // ... data to create a NextBestAction
   *   }
   * })
   * 
   */
  create<T extends NextBestActionCreateArgs>(args: Prisma.SelectSubset<T, NextBestActionCreateArgs<ExtArgs>>): Prisma.Prisma__NextBestActionClient<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many NextBestActions.
   * @param {NextBestActionCreateManyArgs} args - Arguments to create many NextBestActions.
   * @example
   * // Create many NextBestActions
   * const nextBestAction = await prisma.nextBestAction.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends NextBestActionCreateManyArgs>(args?: Prisma.SelectSubset<T, NextBestActionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many NextBestActions and returns the data saved in the database.
   * @param {NextBestActionCreateManyAndReturnArgs} args - Arguments to create many NextBestActions.
   * @example
   * // Create many NextBestActions
   * const nextBestAction = await prisma.nextBestAction.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many NextBestActions and only return the `id`
   * const nextBestActionWithIdOnly = await prisma.nextBestAction.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends NextBestActionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, NextBestActionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a NextBestAction.
   * @param {NextBestActionDeleteArgs} args - Arguments to delete one NextBestAction.
   * @example
   * // Delete one NextBestAction
   * const NextBestAction = await prisma.nextBestAction.delete({
   *   where: {
   *     // ... filter to delete one NextBestAction
   *   }
   * })
   * 
   */
  delete<T extends NextBestActionDeleteArgs>(args: Prisma.SelectSubset<T, NextBestActionDeleteArgs<ExtArgs>>): Prisma.Prisma__NextBestActionClient<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one NextBestAction.
   * @param {NextBestActionUpdateArgs} args - Arguments to update one NextBestAction.
   * @example
   * // Update one NextBestAction
   * const nextBestAction = await prisma.nextBestAction.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends NextBestActionUpdateArgs>(args: Prisma.SelectSubset<T, NextBestActionUpdateArgs<ExtArgs>>): Prisma.Prisma__NextBestActionClient<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more NextBestActions.
   * @param {NextBestActionDeleteManyArgs} args - Arguments to filter NextBestActions to delete.
   * @example
   * // Delete a few NextBestActions
   * const { count } = await prisma.nextBestAction.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends NextBestActionDeleteManyArgs>(args?: Prisma.SelectSubset<T, NextBestActionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NextBestActions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NextBestActionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many NextBestActions
   * const nextBestAction = await prisma.nextBestAction.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends NextBestActionUpdateManyArgs>(args: Prisma.SelectSubset<T, NextBestActionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more NextBestActions and returns the data updated in the database.
   * @param {NextBestActionUpdateManyAndReturnArgs} args - Arguments to update many NextBestActions.
   * @example
   * // Update many NextBestActions
   * const nextBestAction = await prisma.nextBestAction.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more NextBestActions and only return the `id`
   * const nextBestActionWithIdOnly = await prisma.nextBestAction.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends NextBestActionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, NextBestActionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one NextBestAction.
   * @param {NextBestActionUpsertArgs} args - Arguments to update or create a NextBestAction.
   * @example
   * // Update or create a NextBestAction
   * const nextBestAction = await prisma.nextBestAction.upsert({
   *   create: {
   *     // ... data to create a NextBestAction
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the NextBestAction we want to update
   *   }
   * })
   */
  upsert<T extends NextBestActionUpsertArgs>(args: Prisma.SelectSubset<T, NextBestActionUpsertArgs<ExtArgs>>): Prisma.Prisma__NextBestActionClient<runtime.Types.Result.GetResult<Prisma.$NextBestActionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of NextBestActions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NextBestActionCountArgs} args - Arguments to filter NextBestActions to count.
   * @example
   * // Count the number of NextBestActions
   * const count = await prisma.nextBestAction.count({
   *   where: {
   *     // ... the filter for the NextBestActions we want to count
   *   }
   * })
  **/
  count<T extends NextBestActionCountArgs>(
    args?: Prisma.Subset<T, NextBestActionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], NextBestActionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a NextBestAction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NextBestActionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends NextBestActionAggregateArgs>(args: Prisma.Subset<T, NextBestActionAggregateArgs>): Prisma.PrismaPromise<GetNextBestActionAggregateType<T>>

  /**
   * Group by NextBestAction.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {NextBestActionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends NextBestActionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: NextBestActionGroupByArgs['orderBy'] }
      : { orderBy?: NextBestActionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, NextBestActionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetNextBestActionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the NextBestAction model
 */
readonly fields: NextBestActionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for NextBestAction.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__NextBestActionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  journey<T extends Prisma.CommercialJourneyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CommercialJourneyDefaultArgs<ExtArgs>>): Prisma.Prisma__CommercialJourneyClient<runtime.Types.Result.GetResult<Prisma.$CommercialJourneyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  executedAction<T extends Prisma.NextBestAction$executedActionArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.NextBestAction$executedActionArgs<ExtArgs>>): Prisma.Prisma__CommercialActionClient<runtime.Types.Result.GetResult<Prisma.$CommercialActionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the NextBestAction model
 */
export interface NextBestActionFieldRefs {
  readonly id: Prisma.FieldRef<"NextBestAction", 'String'>
  readonly workspaceId: Prisma.FieldRef<"NextBestAction", 'String'>
  readonly journeyId: Prisma.FieldRef<"NextBestAction", 'String'>
  readonly actionType: Prisma.FieldRef<"NextBestAction", 'CommercialActionType'>
  readonly title: Prisma.FieldRef<"NextBestAction", 'String'>
  readonly description: Prisma.FieldRef<"NextBestAction", 'String'>
  readonly reason: Prisma.FieldRef<"NextBestAction", 'String'>
  readonly confidence: Prisma.FieldRef<"NextBestAction", 'Decimal'>
  readonly priority: Prisma.FieldRef<"NextBestAction", 'NextBestActionPriority'>
  readonly source: Prisma.FieldRef<"NextBestAction", 'NextBestActionSource'>
  readonly expiresAt: Prisma.FieldRef<"NextBestAction", 'DateTime'>
  readonly acceptedAt: Prisma.FieldRef<"NextBestAction", 'DateTime'>
  readonly rejectedAt: Prisma.FieldRef<"NextBestAction", 'DateTime'>
  readonly executedActionId: Prisma.FieldRef<"NextBestAction", 'String'>
  readonly createdAt: Prisma.FieldRef<"NextBestAction", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"NextBestAction", 'DateTime'>
}
    

// Custom InputTypes
/**
 * NextBestAction findUnique
 */
export type NextBestActionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * Filter, which NextBestAction to fetch.
   */
  where: Prisma.NextBestActionWhereUniqueInput
}

/**
 * NextBestAction findUniqueOrThrow
 */
export type NextBestActionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * Filter, which NextBestAction to fetch.
   */
  where: Prisma.NextBestActionWhereUniqueInput
}

/**
 * NextBestAction findFirst
 */
export type NextBestActionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * Filter, which NextBestAction to fetch.
   */
  where?: Prisma.NextBestActionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NextBestActions to fetch.
   */
  orderBy?: Prisma.NextBestActionOrderByWithRelationInput | Prisma.NextBestActionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NextBestActions.
   */
  cursor?: Prisma.NextBestActionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NextBestActions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NextBestActions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NextBestActions.
   */
  distinct?: Prisma.NextBestActionScalarFieldEnum | Prisma.NextBestActionScalarFieldEnum[]
}

/**
 * NextBestAction findFirstOrThrow
 */
export type NextBestActionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * Filter, which NextBestAction to fetch.
   */
  where?: Prisma.NextBestActionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NextBestActions to fetch.
   */
  orderBy?: Prisma.NextBestActionOrderByWithRelationInput | Prisma.NextBestActionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for NextBestActions.
   */
  cursor?: Prisma.NextBestActionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NextBestActions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NextBestActions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NextBestActions.
   */
  distinct?: Prisma.NextBestActionScalarFieldEnum | Prisma.NextBestActionScalarFieldEnum[]
}

/**
 * NextBestAction findMany
 */
export type NextBestActionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * Filter, which NextBestActions to fetch.
   */
  where?: Prisma.NextBestActionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of NextBestActions to fetch.
   */
  orderBy?: Prisma.NextBestActionOrderByWithRelationInput | Prisma.NextBestActionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing NextBestActions.
   */
  cursor?: Prisma.NextBestActionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` NextBestActions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` NextBestActions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of NextBestActions.
   */
  distinct?: Prisma.NextBestActionScalarFieldEnum | Prisma.NextBestActionScalarFieldEnum[]
}

/**
 * NextBestAction create
 */
export type NextBestActionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * The data needed to create a NextBestAction.
   */
  data: Prisma.XOR<Prisma.NextBestActionCreateInput, Prisma.NextBestActionUncheckedCreateInput>
}

/**
 * NextBestAction createMany
 */
export type NextBestActionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many NextBestActions.
   */
  data: Prisma.NextBestActionCreateManyInput | Prisma.NextBestActionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * NextBestAction createManyAndReturn
 */
export type NextBestActionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * The data used to create many NextBestActions.
   */
  data: Prisma.NextBestActionCreateManyInput | Prisma.NextBestActionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * NextBestAction update
 */
export type NextBestActionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * The data needed to update a NextBestAction.
   */
  data: Prisma.XOR<Prisma.NextBestActionUpdateInput, Prisma.NextBestActionUncheckedUpdateInput>
  /**
   * Choose, which NextBestAction to update.
   */
  where: Prisma.NextBestActionWhereUniqueInput
}

/**
 * NextBestAction updateMany
 */
export type NextBestActionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update NextBestActions.
   */
  data: Prisma.XOR<Prisma.NextBestActionUpdateManyMutationInput, Prisma.NextBestActionUncheckedUpdateManyInput>
  /**
   * Filter which NextBestActions to update
   */
  where?: Prisma.NextBestActionWhereInput
  /**
   * Limit how many NextBestActions to update.
   */
  limit?: number
}

/**
 * NextBestAction updateManyAndReturn
 */
export type NextBestActionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * The data used to update NextBestActions.
   */
  data: Prisma.XOR<Prisma.NextBestActionUpdateManyMutationInput, Prisma.NextBestActionUncheckedUpdateManyInput>
  /**
   * Filter which NextBestActions to update
   */
  where?: Prisma.NextBestActionWhereInput
  /**
   * Limit how many NextBestActions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * NextBestAction upsert
 */
export type NextBestActionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * The filter to search for the NextBestAction to update in case it exists.
   */
  where: Prisma.NextBestActionWhereUniqueInput
  /**
   * In case the NextBestAction found by the `where` argument doesn't exist, create a new NextBestAction with this data.
   */
  create: Prisma.XOR<Prisma.NextBestActionCreateInput, Prisma.NextBestActionUncheckedCreateInput>
  /**
   * In case the NextBestAction was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.NextBestActionUpdateInput, Prisma.NextBestActionUncheckedUpdateInput>
}

/**
 * NextBestAction delete
 */
export type NextBestActionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
  /**
   * Filter which NextBestAction to delete.
   */
  where: Prisma.NextBestActionWhereUniqueInput
}

/**
 * NextBestAction deleteMany
 */
export type NextBestActionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which NextBestActions to delete
   */
  where?: Prisma.NextBestActionWhereInput
  /**
   * Limit how many NextBestActions to delete.
   */
  limit?: number
}

/**
 * NextBestAction.executedAction
 */
export type NextBestAction$executedActionArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialAction
   */
  select?: Prisma.CommercialActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialAction
   */
  omit?: Prisma.CommercialActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialActionInclude<ExtArgs> | null
  where?: Prisma.CommercialActionWhereInput
}

/**
 * NextBestAction without action
 */
export type NextBestActionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the NextBestAction
   */
  select?: Prisma.NextBestActionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the NextBestAction
   */
  omit?: Prisma.NextBestActionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.NextBestActionInclude<ExtArgs> | null
}
