
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Consortium` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Consortium
 * 
 */
export type ConsortiumModel = runtime.Types.Result.DefaultSelection<Prisma.$ConsortiumPayload>

export type AggregateConsortium = {
  _count: ConsortiumCountAggregateOutputType | null
  _avg: ConsortiumAvgAggregateOutputType | null
  _sum: ConsortiumSumAggregateOutputType | null
  _min: ConsortiumMinAggregateOutputType | null
  _max: ConsortiumMaxAggregateOutputType | null
}

export type ConsortiumAvgAggregateOutputType = {
  minCreditValue: runtime.Decimal | null
  maxCreditValue: runtime.Decimal | null
  defaultTermMonths: number | null
  administrationFeePercent: runtime.Decimal | null
  reserveFundPercent: runtime.Decimal | null
  totalQuotas: number | null
  availableQuotas: number | null
}

export type ConsortiumSumAggregateOutputType = {
  minCreditValue: runtime.Decimal | null
  maxCreditValue: runtime.Decimal | null
  defaultTermMonths: number | null
  administrationFeePercent: runtime.Decimal | null
  reserveFundPercent: runtime.Decimal | null
  totalQuotas: number | null
  availableQuotas: number | null
}

export type ConsortiumMinAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  name: string | null
  administrator: string | null
  type: $Enums.ConsortiumType | null
  groupNumber: string | null
  minCreditValue: runtime.Decimal | null
  maxCreditValue: runtime.Decimal | null
  defaultTermMonths: number | null
  administrationFeePercent: runtime.Decimal | null
  reserveFundPercent: runtime.Decimal | null
  totalQuotas: number | null
  availableQuotas: number | null
  status: $Enums.ConsortiumStatus | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ConsortiumMaxAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  name: string | null
  administrator: string | null
  type: $Enums.ConsortiumType | null
  groupNumber: string | null
  minCreditValue: runtime.Decimal | null
  maxCreditValue: runtime.Decimal | null
  defaultTermMonths: number | null
  administrationFeePercent: runtime.Decimal | null
  reserveFundPercent: runtime.Decimal | null
  totalQuotas: number | null
  availableQuotas: number | null
  status: $Enums.ConsortiumStatus | null
  description: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type ConsortiumCountAggregateOutputType = {
  id: number
  workspaceId: number
  name: number
  administrator: number
  type: number
  groupNumber: number
  minCreditValue: number
  maxCreditValue: number
  defaultTermMonths: number
  administrationFeePercent: number
  reserveFundPercent: number
  totalQuotas: number
  availableQuotas: number
  status: number
  description: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type ConsortiumAvgAggregateInputType = {
  minCreditValue?: true
  maxCreditValue?: true
  defaultTermMonths?: true
  administrationFeePercent?: true
  reserveFundPercent?: true
  totalQuotas?: true
  availableQuotas?: true
}

export type ConsortiumSumAggregateInputType = {
  minCreditValue?: true
  maxCreditValue?: true
  defaultTermMonths?: true
  administrationFeePercent?: true
  reserveFundPercent?: true
  totalQuotas?: true
  availableQuotas?: true
}

export type ConsortiumMinAggregateInputType = {
  id?: true
  workspaceId?: true
  name?: true
  administrator?: true
  type?: true
  groupNumber?: true
  minCreditValue?: true
  maxCreditValue?: true
  defaultTermMonths?: true
  administrationFeePercent?: true
  reserveFundPercent?: true
  totalQuotas?: true
  availableQuotas?: true
  status?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type ConsortiumMaxAggregateInputType = {
  id?: true
  workspaceId?: true
  name?: true
  administrator?: true
  type?: true
  groupNumber?: true
  minCreditValue?: true
  maxCreditValue?: true
  defaultTermMonths?: true
  administrationFeePercent?: true
  reserveFundPercent?: true
  totalQuotas?: true
  availableQuotas?: true
  status?: true
  description?: true
  createdAt?: true
  updatedAt?: true
}

export type ConsortiumCountAggregateInputType = {
  id?: true
  workspaceId?: true
  name?: true
  administrator?: true
  type?: true
  groupNumber?: true
  minCreditValue?: true
  maxCreditValue?: true
  defaultTermMonths?: true
  administrationFeePercent?: true
  reserveFundPercent?: true
  totalQuotas?: true
  availableQuotas?: true
  status?: true
  description?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type ConsortiumAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Consortium to aggregate.
   */
  where?: Prisma.ConsortiumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Consortiums to fetch.
   */
  orderBy?: Prisma.ConsortiumOrderByWithRelationInput | Prisma.ConsortiumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ConsortiumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Consortiums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Consortiums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Consortiums
  **/
  _count?: true | ConsortiumCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ConsortiumAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ConsortiumSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ConsortiumMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ConsortiumMaxAggregateInputType
}

export type GetConsortiumAggregateType<T extends ConsortiumAggregateArgs> = {
      [P in keyof T & keyof AggregateConsortium]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateConsortium[P]>
    : Prisma.GetScalarType<T[P], AggregateConsortium[P]>
}




export type ConsortiumGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ConsortiumWhereInput
  orderBy?: Prisma.ConsortiumOrderByWithAggregationInput | Prisma.ConsortiumOrderByWithAggregationInput[]
  by: Prisma.ConsortiumScalarFieldEnum[] | Prisma.ConsortiumScalarFieldEnum
  having?: Prisma.ConsortiumScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ConsortiumCountAggregateInputType | true
  _avg?: ConsortiumAvgAggregateInputType
  _sum?: ConsortiumSumAggregateInputType
  _min?: ConsortiumMinAggregateInputType
  _max?: ConsortiumMaxAggregateInputType
}

export type ConsortiumGroupByOutputType = {
  id: string
  workspaceId: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal
  maxCreditValue: runtime.Decimal
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal
  reserveFundPercent: runtime.Decimal
  totalQuotas: number
  availableQuotas: number
  status: $Enums.ConsortiumStatus
  description: string | null
  createdAt: Date
  updatedAt: Date
  _count: ConsortiumCountAggregateOutputType | null
  _avg: ConsortiumAvgAggregateOutputType | null
  _sum: ConsortiumSumAggregateOutputType | null
  _min: ConsortiumMinAggregateOutputType | null
  _max: ConsortiumMaxAggregateOutputType | null
}

export type GetConsortiumGroupByPayload<T extends ConsortiumGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ConsortiumGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ConsortiumGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ConsortiumGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ConsortiumGroupByOutputType[P]>
      }
    >
  >



export type ConsortiumWhereInput = {
  AND?: Prisma.ConsortiumWhereInput | Prisma.ConsortiumWhereInput[]
  OR?: Prisma.ConsortiumWhereInput[]
  NOT?: Prisma.ConsortiumWhereInput | Prisma.ConsortiumWhereInput[]
  id?: Prisma.StringFilter<"Consortium"> | string
  workspaceId?: Prisma.StringFilter<"Consortium"> | string
  name?: Prisma.StringFilter<"Consortium"> | string
  administrator?: Prisma.StringFilter<"Consortium"> | string
  type?: Prisma.EnumConsortiumTypeFilter<"Consortium"> | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFilter<"Consortium"> | string
  minCreditValue?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFilter<"Consortium"> | number
  administrationFeePercent?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFilter<"Consortium"> | number
  availableQuotas?: Prisma.IntFilter<"Consortium"> | number
  status?: Prisma.EnumConsortiumStatusFilter<"Consortium"> | $Enums.ConsortiumStatus
  description?: Prisma.StringNullableFilter<"Consortium"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Consortium"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Consortium"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  proposals?: Prisma.ProposalListRelationFilter
  sales?: Prisma.SaleListRelationFilter
}

export type ConsortiumOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  administrator?: Prisma.SortOrder
  type?: Prisma.SortOrder
  groupNumber?: Prisma.SortOrder
  minCreditValue?: Prisma.SortOrder
  maxCreditValue?: Prisma.SortOrder
  defaultTermMonths?: Prisma.SortOrder
  administrationFeePercent?: Prisma.SortOrder
  reserveFundPercent?: Prisma.SortOrder
  totalQuotas?: Prisma.SortOrder
  availableQuotas?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
  proposals?: Prisma.ProposalOrderByRelationAggregateInput
  sales?: Prisma.SaleOrderByRelationAggregateInput
}

export type ConsortiumWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  workspaceId_administrator_groupNumber?: Prisma.ConsortiumWorkspaceIdAdministratorGroupNumberCompoundUniqueInput
  AND?: Prisma.ConsortiumWhereInput | Prisma.ConsortiumWhereInput[]
  OR?: Prisma.ConsortiumWhereInput[]
  NOT?: Prisma.ConsortiumWhereInput | Prisma.ConsortiumWhereInput[]
  workspaceId?: Prisma.StringFilter<"Consortium"> | string
  name?: Prisma.StringFilter<"Consortium"> | string
  administrator?: Prisma.StringFilter<"Consortium"> | string
  type?: Prisma.EnumConsortiumTypeFilter<"Consortium"> | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFilter<"Consortium"> | string
  minCreditValue?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFilter<"Consortium"> | number
  administrationFeePercent?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFilter<"Consortium"> | number
  availableQuotas?: Prisma.IntFilter<"Consortium"> | number
  status?: Prisma.EnumConsortiumStatusFilter<"Consortium"> | $Enums.ConsortiumStatus
  description?: Prisma.StringNullableFilter<"Consortium"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Consortium"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Consortium"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  proposals?: Prisma.ProposalListRelationFilter
  sales?: Prisma.SaleListRelationFilter
}, "id" | "workspaceId_administrator_groupNumber">

export type ConsortiumOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  administrator?: Prisma.SortOrder
  type?: Prisma.SortOrder
  groupNumber?: Prisma.SortOrder
  minCreditValue?: Prisma.SortOrder
  maxCreditValue?: Prisma.SortOrder
  defaultTermMonths?: Prisma.SortOrder
  administrationFeePercent?: Prisma.SortOrder
  reserveFundPercent?: Prisma.SortOrder
  totalQuotas?: Prisma.SortOrder
  availableQuotas?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.ConsortiumCountOrderByAggregateInput
  _avg?: Prisma.ConsortiumAvgOrderByAggregateInput
  _max?: Prisma.ConsortiumMaxOrderByAggregateInput
  _min?: Prisma.ConsortiumMinOrderByAggregateInput
  _sum?: Prisma.ConsortiumSumOrderByAggregateInput
}

export type ConsortiumScalarWhereWithAggregatesInput = {
  AND?: Prisma.ConsortiumScalarWhereWithAggregatesInput | Prisma.ConsortiumScalarWhereWithAggregatesInput[]
  OR?: Prisma.ConsortiumScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ConsortiumScalarWhereWithAggregatesInput | Prisma.ConsortiumScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Consortium"> | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"Consortium"> | string
  name?: Prisma.StringWithAggregatesFilter<"Consortium"> | string
  administrator?: Prisma.StringWithAggregatesFilter<"Consortium"> | string
  type?: Prisma.EnumConsortiumTypeWithAggregatesFilter<"Consortium"> | $Enums.ConsortiumType
  groupNumber?: Prisma.StringWithAggregatesFilter<"Consortium"> | string
  minCreditValue?: Prisma.DecimalWithAggregatesFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalWithAggregatesFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntWithAggregatesFilter<"Consortium"> | number
  administrationFeePercent?: Prisma.DecimalWithAggregatesFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalWithAggregatesFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntWithAggregatesFilter<"Consortium"> | number
  availableQuotas?: Prisma.IntWithAggregatesFilter<"Consortium"> | number
  status?: Prisma.EnumConsortiumStatusWithAggregatesFilter<"Consortium"> | $Enums.ConsortiumStatus
  description?: Prisma.StringNullableWithAggregatesFilter<"Consortium"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Consortium"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Consortium"> | Date | string
}

export type ConsortiumCreateInput = {
  id?: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutConsortiumsInput
  proposals?: Prisma.ProposalCreateNestedManyWithoutConsortiumInput
  sales?: Prisma.SaleCreateNestedManyWithoutConsortiumInput
}

export type ConsortiumUncheckedCreateInput = {
  id?: string
  workspaceId: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  proposals?: Prisma.ProposalUncheckedCreateNestedManyWithoutConsortiumInput
  sales?: Prisma.SaleUncheckedCreateNestedManyWithoutConsortiumInput
}

export type ConsortiumUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutConsortiumsNestedInput
  proposals?: Prisma.ProposalUpdateManyWithoutConsortiumNestedInput
  sales?: Prisma.SaleUpdateManyWithoutConsortiumNestedInput
}

export type ConsortiumUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  proposals?: Prisma.ProposalUncheckedUpdateManyWithoutConsortiumNestedInput
  sales?: Prisma.SaleUncheckedUpdateManyWithoutConsortiumNestedInput
}

export type ConsortiumCreateManyInput = {
  id?: string
  workspaceId: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConsortiumUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConsortiumUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type ConsortiumListRelationFilter = {
  every?: Prisma.ConsortiumWhereInput
  some?: Prisma.ConsortiumWhereInput
  none?: Prisma.ConsortiumWhereInput
}

export type ConsortiumOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ConsortiumWorkspaceIdAdministratorGroupNumberCompoundUniqueInput = {
  workspaceId: string
  administrator: string
  groupNumber: string
}

export type ConsortiumCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  administrator?: Prisma.SortOrder
  type?: Prisma.SortOrder
  groupNumber?: Prisma.SortOrder
  minCreditValue?: Prisma.SortOrder
  maxCreditValue?: Prisma.SortOrder
  defaultTermMonths?: Prisma.SortOrder
  administrationFeePercent?: Prisma.SortOrder
  reserveFundPercent?: Prisma.SortOrder
  totalQuotas?: Prisma.SortOrder
  availableQuotas?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConsortiumAvgOrderByAggregateInput = {
  minCreditValue?: Prisma.SortOrder
  maxCreditValue?: Prisma.SortOrder
  defaultTermMonths?: Prisma.SortOrder
  administrationFeePercent?: Prisma.SortOrder
  reserveFundPercent?: Prisma.SortOrder
  totalQuotas?: Prisma.SortOrder
  availableQuotas?: Prisma.SortOrder
}

export type ConsortiumMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  administrator?: Prisma.SortOrder
  type?: Prisma.SortOrder
  groupNumber?: Prisma.SortOrder
  minCreditValue?: Prisma.SortOrder
  maxCreditValue?: Prisma.SortOrder
  defaultTermMonths?: Prisma.SortOrder
  administrationFeePercent?: Prisma.SortOrder
  reserveFundPercent?: Prisma.SortOrder
  totalQuotas?: Prisma.SortOrder
  availableQuotas?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConsortiumMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  name?: Prisma.SortOrder
  administrator?: Prisma.SortOrder
  type?: Prisma.SortOrder
  groupNumber?: Prisma.SortOrder
  minCreditValue?: Prisma.SortOrder
  maxCreditValue?: Prisma.SortOrder
  defaultTermMonths?: Prisma.SortOrder
  administrationFeePercent?: Prisma.SortOrder
  reserveFundPercent?: Prisma.SortOrder
  totalQuotas?: Prisma.SortOrder
  availableQuotas?: Prisma.SortOrder
  status?: Prisma.SortOrder
  description?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type ConsortiumSumOrderByAggregateInput = {
  minCreditValue?: Prisma.SortOrder
  maxCreditValue?: Prisma.SortOrder
  defaultTermMonths?: Prisma.SortOrder
  administrationFeePercent?: Prisma.SortOrder
  reserveFundPercent?: Prisma.SortOrder
  totalQuotas?: Prisma.SortOrder
  availableQuotas?: Prisma.SortOrder
}

export type ConsortiumScalarRelationFilter = {
  is?: Prisma.ConsortiumWhereInput
  isNot?: Prisma.ConsortiumWhereInput
}

export type ConsortiumCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.ConsortiumCreateWithoutWorkspaceInput, Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput> | Prisma.ConsortiumCreateWithoutWorkspaceInput[] | Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.ConsortiumCreateOrConnectWithoutWorkspaceInput | Prisma.ConsortiumCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.ConsortiumCreateManyWorkspaceInputEnvelope
  connect?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
}

export type ConsortiumUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.ConsortiumCreateWithoutWorkspaceInput, Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput> | Prisma.ConsortiumCreateWithoutWorkspaceInput[] | Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.ConsortiumCreateOrConnectWithoutWorkspaceInput | Prisma.ConsortiumCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.ConsortiumCreateManyWorkspaceInputEnvelope
  connect?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
}

export type ConsortiumUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.ConsortiumCreateWithoutWorkspaceInput, Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput> | Prisma.ConsortiumCreateWithoutWorkspaceInput[] | Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.ConsortiumCreateOrConnectWithoutWorkspaceInput | Prisma.ConsortiumCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.ConsortiumUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.ConsortiumUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.ConsortiumCreateManyWorkspaceInputEnvelope
  set?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
  disconnect?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
  delete?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
  connect?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
  update?: Prisma.ConsortiumUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.ConsortiumUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.ConsortiumUpdateManyWithWhereWithoutWorkspaceInput | Prisma.ConsortiumUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.ConsortiumScalarWhereInput | Prisma.ConsortiumScalarWhereInput[]
}

export type ConsortiumUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.ConsortiumCreateWithoutWorkspaceInput, Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput> | Prisma.ConsortiumCreateWithoutWorkspaceInput[] | Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.ConsortiumCreateOrConnectWithoutWorkspaceInput | Prisma.ConsortiumCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.ConsortiumUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.ConsortiumUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.ConsortiumCreateManyWorkspaceInputEnvelope
  set?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
  disconnect?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
  delete?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
  connect?: Prisma.ConsortiumWhereUniqueInput | Prisma.ConsortiumWhereUniqueInput[]
  update?: Prisma.ConsortiumUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.ConsortiumUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.ConsortiumUpdateManyWithWhereWithoutWorkspaceInput | Prisma.ConsortiumUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.ConsortiumScalarWhereInput | Prisma.ConsortiumScalarWhereInput[]
}

export type EnumConsortiumTypeFieldUpdateOperationsInput = {
  set?: $Enums.ConsortiumType
}

export type EnumConsortiumStatusFieldUpdateOperationsInput = {
  set?: $Enums.ConsortiumStatus
}

export type ConsortiumCreateNestedOneWithoutProposalsInput = {
  create?: Prisma.XOR<Prisma.ConsortiumCreateWithoutProposalsInput, Prisma.ConsortiumUncheckedCreateWithoutProposalsInput>
  connectOrCreate?: Prisma.ConsortiumCreateOrConnectWithoutProposalsInput
  connect?: Prisma.ConsortiumWhereUniqueInput
}

export type ConsortiumUpdateOneRequiredWithoutProposalsNestedInput = {
  create?: Prisma.XOR<Prisma.ConsortiumCreateWithoutProposalsInput, Prisma.ConsortiumUncheckedCreateWithoutProposalsInput>
  connectOrCreate?: Prisma.ConsortiumCreateOrConnectWithoutProposalsInput
  upsert?: Prisma.ConsortiumUpsertWithoutProposalsInput
  connect?: Prisma.ConsortiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ConsortiumUpdateToOneWithWhereWithoutProposalsInput, Prisma.ConsortiumUpdateWithoutProposalsInput>, Prisma.ConsortiumUncheckedUpdateWithoutProposalsInput>
}

export type ConsortiumCreateNestedOneWithoutSalesInput = {
  create?: Prisma.XOR<Prisma.ConsortiumCreateWithoutSalesInput, Prisma.ConsortiumUncheckedCreateWithoutSalesInput>
  connectOrCreate?: Prisma.ConsortiumCreateOrConnectWithoutSalesInput
  connect?: Prisma.ConsortiumWhereUniqueInput
}

export type ConsortiumUpdateOneRequiredWithoutSalesNestedInput = {
  create?: Prisma.XOR<Prisma.ConsortiumCreateWithoutSalesInput, Prisma.ConsortiumUncheckedCreateWithoutSalesInput>
  connectOrCreate?: Prisma.ConsortiumCreateOrConnectWithoutSalesInput
  upsert?: Prisma.ConsortiumUpsertWithoutSalesInput
  connect?: Prisma.ConsortiumWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ConsortiumUpdateToOneWithWhereWithoutSalesInput, Prisma.ConsortiumUpdateWithoutSalesInput>, Prisma.ConsortiumUncheckedUpdateWithoutSalesInput>
}

export type ConsortiumCreateWithoutWorkspaceInput = {
  id?: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  proposals?: Prisma.ProposalCreateNestedManyWithoutConsortiumInput
  sales?: Prisma.SaleCreateNestedManyWithoutConsortiumInput
}

export type ConsortiumUncheckedCreateWithoutWorkspaceInput = {
  id?: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  proposals?: Prisma.ProposalUncheckedCreateNestedManyWithoutConsortiumInput
  sales?: Prisma.SaleUncheckedCreateNestedManyWithoutConsortiumInput
}

export type ConsortiumCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.ConsortiumWhereUniqueInput
  create: Prisma.XOR<Prisma.ConsortiumCreateWithoutWorkspaceInput, Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput>
}

export type ConsortiumCreateManyWorkspaceInputEnvelope = {
  data: Prisma.ConsortiumCreateManyWorkspaceInput | Prisma.ConsortiumCreateManyWorkspaceInput[]
  skipDuplicates?: boolean
}

export type ConsortiumUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.ConsortiumWhereUniqueInput
  update: Prisma.XOR<Prisma.ConsortiumUpdateWithoutWorkspaceInput, Prisma.ConsortiumUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.ConsortiumCreateWithoutWorkspaceInput, Prisma.ConsortiumUncheckedCreateWithoutWorkspaceInput>
}

export type ConsortiumUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.ConsortiumWhereUniqueInput
  data: Prisma.XOR<Prisma.ConsortiumUpdateWithoutWorkspaceInput, Prisma.ConsortiumUncheckedUpdateWithoutWorkspaceInput>
}

export type ConsortiumUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.ConsortiumScalarWhereInput
  data: Prisma.XOR<Prisma.ConsortiumUpdateManyMutationInput, Prisma.ConsortiumUncheckedUpdateManyWithoutWorkspaceInput>
}

export type ConsortiumScalarWhereInput = {
  AND?: Prisma.ConsortiumScalarWhereInput | Prisma.ConsortiumScalarWhereInput[]
  OR?: Prisma.ConsortiumScalarWhereInput[]
  NOT?: Prisma.ConsortiumScalarWhereInput | Prisma.ConsortiumScalarWhereInput[]
  id?: Prisma.StringFilter<"Consortium"> | string
  workspaceId?: Prisma.StringFilter<"Consortium"> | string
  name?: Prisma.StringFilter<"Consortium"> | string
  administrator?: Prisma.StringFilter<"Consortium"> | string
  type?: Prisma.EnumConsortiumTypeFilter<"Consortium"> | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFilter<"Consortium"> | string
  minCreditValue?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFilter<"Consortium"> | number
  administrationFeePercent?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFilter<"Consortium"> | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFilter<"Consortium"> | number
  availableQuotas?: Prisma.IntFilter<"Consortium"> | number
  status?: Prisma.EnumConsortiumStatusFilter<"Consortium"> | $Enums.ConsortiumStatus
  description?: Prisma.StringNullableFilter<"Consortium"> | string | null
  createdAt?: Prisma.DateTimeFilter<"Consortium"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Consortium"> | Date | string
}

export type ConsortiumCreateWithoutProposalsInput = {
  id?: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutConsortiumsInput
  sales?: Prisma.SaleCreateNestedManyWithoutConsortiumInput
}

export type ConsortiumUncheckedCreateWithoutProposalsInput = {
  id?: string
  workspaceId: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  sales?: Prisma.SaleUncheckedCreateNestedManyWithoutConsortiumInput
}

export type ConsortiumCreateOrConnectWithoutProposalsInput = {
  where: Prisma.ConsortiumWhereUniqueInput
  create: Prisma.XOR<Prisma.ConsortiumCreateWithoutProposalsInput, Prisma.ConsortiumUncheckedCreateWithoutProposalsInput>
}

export type ConsortiumUpsertWithoutProposalsInput = {
  update: Prisma.XOR<Prisma.ConsortiumUpdateWithoutProposalsInput, Prisma.ConsortiumUncheckedUpdateWithoutProposalsInput>
  create: Prisma.XOR<Prisma.ConsortiumCreateWithoutProposalsInput, Prisma.ConsortiumUncheckedCreateWithoutProposalsInput>
  where?: Prisma.ConsortiumWhereInput
}

export type ConsortiumUpdateToOneWithWhereWithoutProposalsInput = {
  where?: Prisma.ConsortiumWhereInput
  data: Prisma.XOR<Prisma.ConsortiumUpdateWithoutProposalsInput, Prisma.ConsortiumUncheckedUpdateWithoutProposalsInput>
}

export type ConsortiumUpdateWithoutProposalsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutConsortiumsNestedInput
  sales?: Prisma.SaleUpdateManyWithoutConsortiumNestedInput
}

export type ConsortiumUncheckedUpdateWithoutProposalsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  sales?: Prisma.SaleUncheckedUpdateManyWithoutConsortiumNestedInput
}

export type ConsortiumCreateWithoutSalesInput = {
  id?: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutConsortiumsInput
  proposals?: Prisma.ProposalCreateNestedManyWithoutConsortiumInput
}

export type ConsortiumUncheckedCreateWithoutSalesInput = {
  id?: string
  workspaceId: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  proposals?: Prisma.ProposalUncheckedCreateNestedManyWithoutConsortiumInput
}

export type ConsortiumCreateOrConnectWithoutSalesInput = {
  where: Prisma.ConsortiumWhereUniqueInput
  create: Prisma.XOR<Prisma.ConsortiumCreateWithoutSalesInput, Prisma.ConsortiumUncheckedCreateWithoutSalesInput>
}

export type ConsortiumUpsertWithoutSalesInput = {
  update: Prisma.XOR<Prisma.ConsortiumUpdateWithoutSalesInput, Prisma.ConsortiumUncheckedUpdateWithoutSalesInput>
  create: Prisma.XOR<Prisma.ConsortiumCreateWithoutSalesInput, Prisma.ConsortiumUncheckedCreateWithoutSalesInput>
  where?: Prisma.ConsortiumWhereInput
}

export type ConsortiumUpdateToOneWithWhereWithoutSalesInput = {
  where?: Prisma.ConsortiumWhereInput
  data: Prisma.XOR<Prisma.ConsortiumUpdateWithoutSalesInput, Prisma.ConsortiumUncheckedUpdateWithoutSalesInput>
}

export type ConsortiumUpdateWithoutSalesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutConsortiumsNestedInput
  proposals?: Prisma.ProposalUpdateManyWithoutConsortiumNestedInput
}

export type ConsortiumUncheckedUpdateWithoutSalesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  proposals?: Prisma.ProposalUncheckedUpdateManyWithoutConsortiumNestedInput
}

export type ConsortiumCreateManyWorkspaceInput = {
  id?: string
  name: string
  administrator: string
  type: $Enums.ConsortiumType
  groupNumber: string
  minCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue: runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths: number
  administrationFeePercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent: runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas: number
  availableQuotas: number
  status?: $Enums.ConsortiumStatus
  description?: string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type ConsortiumUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  proposals?: Prisma.ProposalUpdateManyWithoutConsortiumNestedInput
  sales?: Prisma.SaleUpdateManyWithoutConsortiumNestedInput
}

export type ConsortiumUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  proposals?: Prisma.ProposalUncheckedUpdateManyWithoutConsortiumNestedInput
  sales?: Prisma.SaleUncheckedUpdateManyWithoutConsortiumNestedInput
}

export type ConsortiumUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  administrator?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumConsortiumTypeFieldUpdateOperationsInput | $Enums.ConsortiumType
  groupNumber?: Prisma.StringFieldUpdateOperationsInput | string
  minCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  maxCreditValue?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  defaultTermMonths?: Prisma.IntFieldUpdateOperationsInput | number
  administrationFeePercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  reserveFundPercent?: Prisma.DecimalFieldUpdateOperationsInput | runtime.Decimal | runtime.DecimalJsLike | number | string
  totalQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  availableQuotas?: Prisma.IntFieldUpdateOperationsInput | number
  status?: Prisma.EnumConsortiumStatusFieldUpdateOperationsInput | $Enums.ConsortiumStatus
  description?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type ConsortiumCountOutputType
 */

export type ConsortiumCountOutputType = {
  proposals: number
  sales: number
}

export type ConsortiumCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  proposals?: boolean | ConsortiumCountOutputTypeCountProposalsArgs
  sales?: boolean | ConsortiumCountOutputTypeCountSalesArgs
}

/**
 * ConsortiumCountOutputType without action
 */
export type ConsortiumCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ConsortiumCountOutputType
   */
  select?: Prisma.ConsortiumCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ConsortiumCountOutputType without action
 */
export type ConsortiumCountOutputTypeCountProposalsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ProposalWhereInput
}

/**
 * ConsortiumCountOutputType without action
 */
export type ConsortiumCountOutputTypeCountSalesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.SaleWhereInput
}


export type ConsortiumSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  name?: boolean
  administrator?: boolean
  type?: boolean
  groupNumber?: boolean
  minCreditValue?: boolean
  maxCreditValue?: boolean
  defaultTermMonths?: boolean
  administrationFeePercent?: boolean
  reserveFundPercent?: boolean
  totalQuotas?: boolean
  availableQuotas?: boolean
  status?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  proposals?: boolean | Prisma.Consortium$proposalsArgs<ExtArgs>
  sales?: boolean | Prisma.Consortium$salesArgs<ExtArgs>
  _count?: boolean | Prisma.ConsortiumCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["consortium"]>

export type ConsortiumSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  name?: boolean
  administrator?: boolean
  type?: boolean
  groupNumber?: boolean
  minCreditValue?: boolean
  maxCreditValue?: boolean
  defaultTermMonths?: boolean
  administrationFeePercent?: boolean
  reserveFundPercent?: boolean
  totalQuotas?: boolean
  availableQuotas?: boolean
  status?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["consortium"]>

export type ConsortiumSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  name?: boolean
  administrator?: boolean
  type?: boolean
  groupNumber?: boolean
  minCreditValue?: boolean
  maxCreditValue?: boolean
  defaultTermMonths?: boolean
  administrationFeePercent?: boolean
  reserveFundPercent?: boolean
  totalQuotas?: boolean
  availableQuotas?: boolean
  status?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["consortium"]>

export type ConsortiumSelectScalar = {
  id?: boolean
  workspaceId?: boolean
  name?: boolean
  administrator?: boolean
  type?: boolean
  groupNumber?: boolean
  minCreditValue?: boolean
  maxCreditValue?: boolean
  defaultTermMonths?: boolean
  administrationFeePercent?: boolean
  reserveFundPercent?: boolean
  totalQuotas?: boolean
  availableQuotas?: boolean
  status?: boolean
  description?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type ConsortiumOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workspaceId" | "name" | "administrator" | "type" | "groupNumber" | "minCreditValue" | "maxCreditValue" | "defaultTermMonths" | "administrationFeePercent" | "reserveFundPercent" | "totalQuotas" | "availableQuotas" | "status" | "description" | "createdAt" | "updatedAt", ExtArgs["result"]["consortium"]>
export type ConsortiumInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  proposals?: boolean | Prisma.Consortium$proposalsArgs<ExtArgs>
  sales?: boolean | Prisma.Consortium$salesArgs<ExtArgs>
  _count?: boolean | Prisma.ConsortiumCountOutputTypeDefaultArgs<ExtArgs>
}
export type ConsortiumIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}
export type ConsortiumIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
}

export type $ConsortiumPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Consortium"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
    proposals: Prisma.$ProposalPayload<ExtArgs>[]
    sales: Prisma.$SalePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    workspaceId: string
    name: string
    administrator: string
    type: $Enums.ConsortiumType
    groupNumber: string
    minCreditValue: runtime.Decimal
    maxCreditValue: runtime.Decimal
    defaultTermMonths: number
    administrationFeePercent: runtime.Decimal
    reserveFundPercent: runtime.Decimal
    totalQuotas: number
    availableQuotas: number
    status: $Enums.ConsortiumStatus
    description: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["consortium"]>
  composites: {}
}

export type ConsortiumGetPayload<S extends boolean | null | undefined | ConsortiumDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload, S>

export type ConsortiumCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ConsortiumFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ConsortiumCountAggregateInputType | true
  }

export interface ConsortiumDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Consortium'], meta: { name: 'Consortium' } }
  /**
   * Find zero or one Consortium that matches the filter.
   * @param {ConsortiumFindUniqueArgs} args - Arguments to find a Consortium
   * @example
   * // Get one Consortium
   * const consortium = await prisma.consortium.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ConsortiumFindUniqueArgs>(args: Prisma.SelectSubset<T, ConsortiumFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ConsortiumClient<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Consortium that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ConsortiumFindUniqueOrThrowArgs} args - Arguments to find a Consortium
   * @example
   * // Get one Consortium
   * const consortium = await prisma.consortium.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ConsortiumFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ConsortiumFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConsortiumClient<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Consortium that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsortiumFindFirstArgs} args - Arguments to find a Consortium
   * @example
   * // Get one Consortium
   * const consortium = await prisma.consortium.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ConsortiumFindFirstArgs>(args?: Prisma.SelectSubset<T, ConsortiumFindFirstArgs<ExtArgs>>): Prisma.Prisma__ConsortiumClient<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Consortium that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsortiumFindFirstOrThrowArgs} args - Arguments to find a Consortium
   * @example
   * // Get one Consortium
   * const consortium = await prisma.consortium.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ConsortiumFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ConsortiumFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ConsortiumClient<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Consortiums that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsortiumFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Consortiums
   * const consortiums = await prisma.consortium.findMany()
   * 
   * // Get first 10 Consortiums
   * const consortiums = await prisma.consortium.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const consortiumWithIdOnly = await prisma.consortium.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ConsortiumFindManyArgs>(args?: Prisma.SelectSubset<T, ConsortiumFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Consortium.
   * @param {ConsortiumCreateArgs} args - Arguments to create a Consortium.
   * @example
   * // Create one Consortium
   * const Consortium = await prisma.consortium.create({
   *   data: {
   *     // ... data to create a Consortium
   *   }
   * })
   * 
   */
  create<T extends ConsortiumCreateArgs>(args: Prisma.SelectSubset<T, ConsortiumCreateArgs<ExtArgs>>): Prisma.Prisma__ConsortiumClient<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Consortiums.
   * @param {ConsortiumCreateManyArgs} args - Arguments to create many Consortiums.
   * @example
   * // Create many Consortiums
   * const consortium = await prisma.consortium.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ConsortiumCreateManyArgs>(args?: Prisma.SelectSubset<T, ConsortiumCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Consortiums and returns the data saved in the database.
   * @param {ConsortiumCreateManyAndReturnArgs} args - Arguments to create many Consortiums.
   * @example
   * // Create many Consortiums
   * const consortium = await prisma.consortium.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Consortiums and only return the `id`
   * const consortiumWithIdOnly = await prisma.consortium.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ConsortiumCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ConsortiumCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Consortium.
   * @param {ConsortiumDeleteArgs} args - Arguments to delete one Consortium.
   * @example
   * // Delete one Consortium
   * const Consortium = await prisma.consortium.delete({
   *   where: {
   *     // ... filter to delete one Consortium
   *   }
   * })
   * 
   */
  delete<T extends ConsortiumDeleteArgs>(args: Prisma.SelectSubset<T, ConsortiumDeleteArgs<ExtArgs>>): Prisma.Prisma__ConsortiumClient<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Consortium.
   * @param {ConsortiumUpdateArgs} args - Arguments to update one Consortium.
   * @example
   * // Update one Consortium
   * const consortium = await prisma.consortium.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ConsortiumUpdateArgs>(args: Prisma.SelectSubset<T, ConsortiumUpdateArgs<ExtArgs>>): Prisma.Prisma__ConsortiumClient<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Consortiums.
   * @param {ConsortiumDeleteManyArgs} args - Arguments to filter Consortiums to delete.
   * @example
   * // Delete a few Consortiums
   * const { count } = await prisma.consortium.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ConsortiumDeleteManyArgs>(args?: Prisma.SelectSubset<T, ConsortiumDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Consortiums.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsortiumUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Consortiums
   * const consortium = await prisma.consortium.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ConsortiumUpdateManyArgs>(args: Prisma.SelectSubset<T, ConsortiumUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Consortiums and returns the data updated in the database.
   * @param {ConsortiumUpdateManyAndReturnArgs} args - Arguments to update many Consortiums.
   * @example
   * // Update many Consortiums
   * const consortium = await prisma.consortium.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Consortiums and only return the `id`
   * const consortiumWithIdOnly = await prisma.consortium.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ConsortiumUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ConsortiumUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Consortium.
   * @param {ConsortiumUpsertArgs} args - Arguments to update or create a Consortium.
   * @example
   * // Update or create a Consortium
   * const consortium = await prisma.consortium.upsert({
   *   create: {
   *     // ... data to create a Consortium
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Consortium we want to update
   *   }
   * })
   */
  upsert<T extends ConsortiumUpsertArgs>(args: Prisma.SelectSubset<T, ConsortiumUpsertArgs<ExtArgs>>): Prisma.Prisma__ConsortiumClient<runtime.Types.Result.GetResult<Prisma.$ConsortiumPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Consortiums.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsortiumCountArgs} args - Arguments to filter Consortiums to count.
   * @example
   * // Count the number of Consortiums
   * const count = await prisma.consortium.count({
   *   where: {
   *     // ... the filter for the Consortiums we want to count
   *   }
   * })
  **/
  count<T extends ConsortiumCountArgs>(
    args?: Prisma.Subset<T, ConsortiumCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ConsortiumCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Consortium.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsortiumAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ConsortiumAggregateArgs>(args: Prisma.Subset<T, ConsortiumAggregateArgs>): Prisma.PrismaPromise<GetConsortiumAggregateType<T>>

  /**
   * Group by Consortium.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ConsortiumGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ConsortiumGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ConsortiumGroupByArgs['orderBy'] }
      : { orderBy?: ConsortiumGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ConsortiumGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetConsortiumGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Consortium model
 */
readonly fields: ConsortiumFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Consortium.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ConsortiumClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  proposals<T extends Prisma.Consortium$proposalsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Consortium$proposalsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ProposalPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  sales<T extends Prisma.Consortium$salesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Consortium$salesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$SalePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Consortium model
 */
export interface ConsortiumFieldRefs {
  readonly id: Prisma.FieldRef<"Consortium", 'String'>
  readonly workspaceId: Prisma.FieldRef<"Consortium", 'String'>
  readonly name: Prisma.FieldRef<"Consortium", 'String'>
  readonly administrator: Prisma.FieldRef<"Consortium", 'String'>
  readonly type: Prisma.FieldRef<"Consortium", 'ConsortiumType'>
  readonly groupNumber: Prisma.FieldRef<"Consortium", 'String'>
  readonly minCreditValue: Prisma.FieldRef<"Consortium", 'Decimal'>
  readonly maxCreditValue: Prisma.FieldRef<"Consortium", 'Decimal'>
  readonly defaultTermMonths: Prisma.FieldRef<"Consortium", 'Int'>
  readonly administrationFeePercent: Prisma.FieldRef<"Consortium", 'Decimal'>
  readonly reserveFundPercent: Prisma.FieldRef<"Consortium", 'Decimal'>
  readonly totalQuotas: Prisma.FieldRef<"Consortium", 'Int'>
  readonly availableQuotas: Prisma.FieldRef<"Consortium", 'Int'>
  readonly status: Prisma.FieldRef<"Consortium", 'ConsortiumStatus'>
  readonly description: Prisma.FieldRef<"Consortium", 'String'>
  readonly createdAt: Prisma.FieldRef<"Consortium", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Consortium", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Consortium findUnique
 */
export type ConsortiumFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * Filter, which Consortium to fetch.
   */
  where: Prisma.ConsortiumWhereUniqueInput
}

/**
 * Consortium findUniqueOrThrow
 */
export type ConsortiumFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * Filter, which Consortium to fetch.
   */
  where: Prisma.ConsortiumWhereUniqueInput
}

/**
 * Consortium findFirst
 */
export type ConsortiumFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * Filter, which Consortium to fetch.
   */
  where?: Prisma.ConsortiumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Consortiums to fetch.
   */
  orderBy?: Prisma.ConsortiumOrderByWithRelationInput | Prisma.ConsortiumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Consortiums.
   */
  cursor?: Prisma.ConsortiumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Consortiums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Consortiums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Consortiums.
   */
  distinct?: Prisma.ConsortiumScalarFieldEnum | Prisma.ConsortiumScalarFieldEnum[]
}

/**
 * Consortium findFirstOrThrow
 */
export type ConsortiumFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * Filter, which Consortium to fetch.
   */
  where?: Prisma.ConsortiumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Consortiums to fetch.
   */
  orderBy?: Prisma.ConsortiumOrderByWithRelationInput | Prisma.ConsortiumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Consortiums.
   */
  cursor?: Prisma.ConsortiumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Consortiums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Consortiums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Consortiums.
   */
  distinct?: Prisma.ConsortiumScalarFieldEnum | Prisma.ConsortiumScalarFieldEnum[]
}

/**
 * Consortium findMany
 */
export type ConsortiumFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * Filter, which Consortiums to fetch.
   */
  where?: Prisma.ConsortiumWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Consortiums to fetch.
   */
  orderBy?: Prisma.ConsortiumOrderByWithRelationInput | Prisma.ConsortiumOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Consortiums.
   */
  cursor?: Prisma.ConsortiumWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Consortiums from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Consortiums.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Consortiums.
   */
  distinct?: Prisma.ConsortiumScalarFieldEnum | Prisma.ConsortiumScalarFieldEnum[]
}

/**
 * Consortium create
 */
export type ConsortiumCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * The data needed to create a Consortium.
   */
  data: Prisma.XOR<Prisma.ConsortiumCreateInput, Prisma.ConsortiumUncheckedCreateInput>
}

/**
 * Consortium createMany
 */
export type ConsortiumCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Consortiums.
   */
  data: Prisma.ConsortiumCreateManyInput | Prisma.ConsortiumCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Consortium createManyAndReturn
 */
export type ConsortiumCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * The data used to create many Consortiums.
   */
  data: Prisma.ConsortiumCreateManyInput | Prisma.ConsortiumCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Consortium update
 */
export type ConsortiumUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * The data needed to update a Consortium.
   */
  data: Prisma.XOR<Prisma.ConsortiumUpdateInput, Prisma.ConsortiumUncheckedUpdateInput>
  /**
   * Choose, which Consortium to update.
   */
  where: Prisma.ConsortiumWhereUniqueInput
}

/**
 * Consortium updateMany
 */
export type ConsortiumUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Consortiums.
   */
  data: Prisma.XOR<Prisma.ConsortiumUpdateManyMutationInput, Prisma.ConsortiumUncheckedUpdateManyInput>
  /**
   * Filter which Consortiums to update
   */
  where?: Prisma.ConsortiumWhereInput
  /**
   * Limit how many Consortiums to update.
   */
  limit?: number
}

/**
 * Consortium updateManyAndReturn
 */
export type ConsortiumUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * The data used to update Consortiums.
   */
  data: Prisma.XOR<Prisma.ConsortiumUpdateManyMutationInput, Prisma.ConsortiumUncheckedUpdateManyInput>
  /**
   * Filter which Consortiums to update
   */
  where?: Prisma.ConsortiumWhereInput
  /**
   * Limit how many Consortiums to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Consortium upsert
 */
export type ConsortiumUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * The filter to search for the Consortium to update in case it exists.
   */
  where: Prisma.ConsortiumWhereUniqueInput
  /**
   * In case the Consortium found by the `where` argument doesn't exist, create a new Consortium with this data.
   */
  create: Prisma.XOR<Prisma.ConsortiumCreateInput, Prisma.ConsortiumUncheckedCreateInput>
  /**
   * In case the Consortium was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ConsortiumUpdateInput, Prisma.ConsortiumUncheckedUpdateInput>
}

/**
 * Consortium delete
 */
export type ConsortiumDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
  /**
   * Filter which Consortium to delete.
   */
  where: Prisma.ConsortiumWhereUniqueInput
}

/**
 * Consortium deleteMany
 */
export type ConsortiumDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Consortiums to delete
   */
  where?: Prisma.ConsortiumWhereInput
  /**
   * Limit how many Consortiums to delete.
   */
  limit?: number
}

/**
 * Consortium.proposals
 */
export type Consortium$proposalsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Proposal
   */
  select?: Prisma.ProposalSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Proposal
   */
  omit?: Prisma.ProposalOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ProposalInclude<ExtArgs> | null
  where?: Prisma.ProposalWhereInput
  orderBy?: Prisma.ProposalOrderByWithRelationInput | Prisma.ProposalOrderByWithRelationInput[]
  cursor?: Prisma.ProposalWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ProposalScalarFieldEnum | Prisma.ProposalScalarFieldEnum[]
}

/**
 * Consortium.sales
 */
export type Consortium$salesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Sale
   */
  select?: Prisma.SaleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Sale
   */
  omit?: Prisma.SaleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.SaleInclude<ExtArgs> | null
  where?: Prisma.SaleWhereInput
  orderBy?: Prisma.SaleOrderByWithRelationInput | Prisma.SaleOrderByWithRelationInput[]
  cursor?: Prisma.SaleWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.SaleScalarFieldEnum | Prisma.SaleScalarFieldEnum[]
}

/**
 * Consortium without action
 */
export type ConsortiumDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Consortium
   */
  select?: Prisma.ConsortiumSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Consortium
   */
  omit?: Prisma.ConsortiumOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ConsortiumInclude<ExtArgs> | null
}
