
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model Workspace
 * 
 */
export type Workspace = Prisma.WorkspaceModel
/**
 * Model Consultant
 * 
 */
export type Consultant = Prisma.ConsultantModel
/**
 * Model Consortium
 * 
 */
export type Consortium = Prisma.ConsortiumModel
/**
 * Model PipelineStage
 * 
 */
export type PipelineStage = Prisma.PipelineStageModel
/**
 * Model Lead
 * 
 */
export type Lead = Prisma.LeadModel
/**
 * Model Client
 * 
 */
export type Client = Prisma.ClientModel
/**
 * Model Proposal
 * 
 */
export type Proposal = Prisma.ProposalModel
/**
 * Model Meeting
 * 
 */
export type Meeting = Prisma.MeetingModel
/**
 * Model Sale
 * 
 */
export type Sale = Prisma.SaleModel
/**
 * Model Task
 * 
 */
export type Task = Prisma.TaskModel
/**
 * Model JourneyPhase
 * 
 */
export type JourneyPhase = Prisma.JourneyPhaseModel
/**
 * Model JourneyState
 * 
 */
export type JourneyState = Prisma.JourneyStateModel
/**
 * Model CommercialJourney
 * 
 */
export type CommercialJourney = Prisma.CommercialJourneyModel
/**
 * Model CommercialEvent
 * 
 */
export type CommercialEvent = Prisma.CommercialEventModel
/**
 * Model CommercialAction
 * 
 */
export type CommercialAction = Prisma.CommercialActionModel
/**
 * Model WorkflowRule
 * 
 */
export type WorkflowRule = Prisma.WorkflowRuleModel
/**
 * Model NextBestAction
 * 
 */
export type NextBestAction = Prisma.NextBestActionModel
