
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const WorkspaceStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE'
} as const

export type WorkspaceStatus = (typeof WorkspaceStatus)[keyof typeof WorkspaceStatus]


export const ConsultantRole = {
  CONSULTANT: 'CONSULTANT',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN'
} as const

export type ConsultantRole = (typeof ConsultantRole)[keyof typeof ConsultantRole]


export const ConsultantStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  ON_LEAVE: 'ON_LEAVE'
} as const

export type ConsultantStatus = (typeof ConsultantStatus)[keyof typeof ConsultantStatus]


export const ConsortiumType = {
  REAL_ESTATE: 'REAL_ESTATE',
  VEHICLE: 'VEHICLE',
  HEAVY_VEHICLE: 'HEAVY_VEHICLE',
  SERVICES: 'SERVICES',
  OTHER: 'OTHER'
} as const

export type ConsortiumType = (typeof ConsortiumType)[keyof typeof ConsortiumType]


export const ConsortiumStatus = {
  FORMING: 'FORMING',
  ACTIVE: 'ACTIVE',
  CLOSED: 'CLOSED'
} as const

export type ConsortiumStatus = (typeof ConsortiumStatus)[keyof typeof ConsortiumStatus]


export const PipelineStageType = {
  LEAD: 'LEAD',
  DEAL: 'DEAL'
} as const

export type PipelineStageType = (typeof PipelineStageType)[keyof typeof PipelineStageType]


export const LeadSource = {
  REFERRAL: 'REFERRAL',
  WEBSITE: 'WEBSITE',
  SOCIAL_MEDIA: 'SOCIAL_MEDIA',
  COLD_CALL: 'COLD_CALL',
  EVENT: 'EVENT',
  PARTNER: 'PARTNER',
  WALK_IN: 'WALK_IN',
  OTHER: 'OTHER'
} as const

export type LeadSource = (typeof LeadSource)[keyof typeof LeadSource]


export const LeadStatus = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  QUALIFIED: 'QUALIFIED',
  NEGOTIATING: 'NEGOTIATING',
  CONVERTED: 'CONVERTED',
  LOST: 'LOST'
} as const

export type LeadStatus = (typeof LeadStatus)[keyof typeof LeadStatus]


export const PersonType = {
  INDIVIDUAL: 'INDIVIDUAL',
  COMPANY: 'COMPANY'
} as const

export type PersonType = (typeof PersonType)[keyof typeof PersonType]


export const ClientStatus = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
  BLOCKED: 'BLOCKED'
} as const

export type ClientStatus = (typeof ClientStatus)[keyof typeof ClientStatus]


export const ProposalStatus = {
  DRAFT: 'DRAFT',
  SENT: 'SENT',
  ACCEPTED: 'ACCEPTED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED'
} as const

export type ProposalStatus = (typeof ProposalStatus)[keyof typeof ProposalStatus]


export const MeetingType = {
  IN_PERSON: 'IN_PERSON',
  ONLINE: 'ONLINE',
  PHONE: 'PHONE'
} as const

export type MeetingType = (typeof MeetingType)[keyof typeof MeetingType]


export const MeetingStatus = {
  SCHEDULED: 'SCHEDULED',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
  NO_SHOW: 'NO_SHOW'
} as const

export type MeetingStatus = (typeof MeetingStatus)[keyof typeof MeetingStatus]


export const MeetingOutcome = {
  PROPOSAL_SENT: 'PROPOSAL_SENT',
  FOLLOW_UP_SCHEDULED: 'FOLLOW_UP_SCHEDULED',
  NOT_INTERESTED: 'NOT_INTERESTED',
  CONVERTED: 'CONVERTED',
  NO_ANSWER: 'NO_ANSWER',
  OTHER: 'OTHER'
} as const

export type MeetingOutcome = (typeof MeetingOutcome)[keyof typeof MeetingOutcome]


export const SaleStatus = {
  PENDING_SIGNATURE: 'PENDING_SIGNATURE',
  ACTIVE: 'ACTIVE',
  CANCELLED: 'CANCELLED'
} as const

export type SaleStatus = (typeof SaleStatus)[keyof typeof SaleStatus]


export const QuotaStatus = {
  NOT_CONTEMPLATED: 'NOT_CONTEMPLATED',
  CONTEMPLATED: 'CONTEMPLATED',
  PAID_OFF: 'PAID_OFF',
  CANCELLED: 'CANCELLED'
} as const

export type QuotaStatus = (typeof QuotaStatus)[keyof typeof QuotaStatus]


export const PaymentMethod = {
  BANK_SLIP: 'BANK_SLIP',
  DIRECT_DEBIT: 'DIRECT_DEBIT',
  CREDIT_CARD: 'CREDIT_CARD',
  PIX: 'PIX'
} as const

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod]


export const TaskPriority = {
  HIGH: 'HIGH',
  MEDIUM: 'MEDIUM',
  LOW: 'LOW'
} as const

export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority]


export const TaskStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
} as const

export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]


export const TaskType = {
  CALL: 'CALL',
  EMAIL: 'EMAIL',
  FOLLOW_UP: 'FOLLOW_UP',
  DOCUMENT: 'DOCUMENT',
  MEETING_PREP: 'MEETING_PREP',
  PROPOSAL_REVIEW: 'PROPOSAL_REVIEW',
  OTHER: 'OTHER'
} as const

export type TaskType = (typeof TaskType)[keyof typeof TaskType]


export const CommercialJourneyPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
} as const

export type CommercialJourneyPriority = (typeof CommercialJourneyPriority)[keyof typeof CommercialJourneyPriority]


export const CommercialJourneyOutcome = {
  WON: 'WON',
  LOST_TO_COMPETITOR: 'LOST_TO_COMPETITOR',
  NO_FINANCIAL_CAPACITY: 'NO_FINANCIAL_CAPACITY',
  NO_RESPONSE: 'NO_RESPONSE',
  POSTPONED: 'POSTPONED',
  PRODUCT_NOT_SUITABLE: 'PRODUCT_NOT_SUITABLE',
  TRUST_CONCERN: 'TRUST_CONCERN',
  CLIENT_WITHDREW: 'CLIENT_WITHDREW',
  CANCELLED_BY_CONSULTANT: 'CANCELLED_BY_CONSULTANT',
  OTHER: 'OTHER'
} as const

export type CommercialJourneyOutcome = (typeof CommercialJourneyOutcome)[keyof typeof CommercialJourneyOutcome]


export const CommercialActorType = {
  LEAD: 'LEAD',
  CLIENT: 'CLIENT',
  CONSULTANT: 'CONSULTANT',
  AI: 'AI',
  SYSTEM: 'SYSTEM',
  AUTOMATION: 'AUTOMATION',
  ADMINISTRATOR: 'ADMINISTRATOR'
} as const

export type CommercialActorType = (typeof CommercialActorType)[keyof typeof CommercialActorType]


export const CommercialEventType = {
  LEAD_CREATED: 'LEAD_CREATED',
  LEAD_REPLIED: 'LEAD_REPLIED',
  MEETING_SCHEDULED: 'MEETING_SCHEDULED',
  MEETING_COMPLETED: 'MEETING_COMPLETED',
  PROPOSAL_SENT: 'PROPOSAL_SENT',
  PROPOSAL_ACCEPTED: 'PROPOSAL_ACCEPTED',
  DOCUMENT_REQUESTED: 'DOCUMENT_REQUESTED',
  DOCUMENT_RECEIVED: 'DOCUMENT_RECEIVED',
  PAYMENT_CONFIRMED: 'PAYMENT_CONFIRMED',
  SALE_COMPLETED: 'SALE_COMPLETED',
  STATE_CHANGED: 'STATE_CHANGED',
  NOTE_ADDED: 'NOTE_ADDED',
  TASK_CREATED: 'TASK_CREATED',
  TASK_COMPLETED: 'TASK_COMPLETED'
} as const

export type CommercialEventType = (typeof CommercialEventType)[keyof typeof CommercialEventType]


export const CommercialActionType = {
  CHANGE_STATE: 'CHANGE_STATE',
  CREATE_TASK: 'CREATE_TASK',
  COMPLETE_TASK: 'COMPLETE_TASK',
  ADD_NOTE: 'ADD_NOTE',
  UPDATE_PRIORITY: 'UPDATE_PRIORITY',
  UPDATE_SCORE: 'UPDATE_SCORE',
  ASSIGN_CONSULTANT: 'ASSIGN_CONSULTANT',
  SEND_NOTIFICATION: 'SEND_NOTIFICATION',
  SEND_MESSAGE: 'SEND_MESSAGE',
  REQUEST_DOCUMENT: 'REQUEST_DOCUMENT',
  CREATE_PROPOSAL: 'CREATE_PROPOSAL',
  TRIGGER_AUTOMATION: 'TRIGGER_AUTOMATION'
} as const

export type CommercialActionType = (typeof CommercialActionType)[keyof typeof CommercialActionType]


export const CommercialActionStatus = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED'
} as const

export type CommercialActionStatus = (typeof CommercialActionStatus)[keyof typeof CommercialActionStatus]


export const CommercialActionOrigin = {
  MANUAL: 'MANUAL',
  WORKFLOW_RULE: 'WORKFLOW_RULE',
  NEXT_BEST_ACTION: 'NEXT_BEST_ACTION',
  AI: 'AI',
  SYSTEM: 'SYSTEM'
} as const

export type CommercialActionOrigin = (typeof CommercialActionOrigin)[keyof typeof CommercialActionOrigin]


export const NextBestActionSource = {
  RULE_ENGINE: 'RULE_ENGINE',
  AI: 'AI',
  SYSTEM: 'SYSTEM',
  CONSULTANT: 'CONSULTANT'
} as const

export type NextBestActionSource = (typeof NextBestActionSource)[keyof typeof NextBestActionSource]


export const NextBestActionPriority = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
} as const

export type NextBestActionPriority = (typeof NextBestActionPriority)[keyof typeof NextBestActionPriority]
