
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Workspace'
export type * from './models/Consultant'
export type * from './models/Consortium'
export type * from './models/PipelineStage'
export type * from './models/Lead'
export type * from './models/Client'
export type * from './models/Proposal'
export type * from './models/Meeting'
export type * from './models/Sale'
export type * from './models/Task'
export type * from './models/JourneyPhase'
export type * from './models/JourneyState'
export type * from './models/CommercialJourney'
export type * from './models/CommercialEvent'
export type * from './models/CommercialAction'
export type * from './models/WorkflowRule'
export type * from './models/NextBestAction'
export type * from './commonInputTypes'