
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports various common sort, input & filter types that are not directly linked to a particular model.
 *
 * 🟢 You can import this file directly.
 */

import type * as runtime from "@prisma/client/runtime/client"
import * as $Enums from "./enums"
import type * as Prisma from "./internal/prismaNamespace"


export type StringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type EnumWorkspaceStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.WorkspaceStatus | Prisma.EnumWorkspaceStatusFieldRefInput<$PrismaModel>
  in?: $Enums.WorkspaceStatus[] | Prisma.ListEnumWorkspaceStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorkspaceStatus[] | Prisma.ListEnumWorkspaceStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorkspaceStatusFilter<$PrismaModel> | $Enums.WorkspaceStatus
}

export type DateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type StringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type EnumWorkspaceStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WorkspaceStatus | Prisma.EnumWorkspaceStatusFieldRefInput<$PrismaModel>
  in?: $Enums.WorkspaceStatus[] | Prisma.ListEnumWorkspaceStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorkspaceStatus[] | Prisma.ListEnumWorkspaceStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorkspaceStatusWithAggregatesFilter<$PrismaModel> | $Enums.WorkspaceStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWorkspaceStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWorkspaceStatusFilter<$PrismaModel>
}

export type DateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type EnumConsultantRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsultantRole | Prisma.EnumConsultantRoleFieldRefInput<$PrismaModel>
  in?: $Enums.ConsultantRole[] | Prisma.ListEnumConsultantRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsultantRole[] | Prisma.ListEnumConsultantRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsultantRoleFilter<$PrismaModel> | $Enums.ConsultantRole
}

export type StringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type EnumConsultantStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsultantStatus | Prisma.EnumConsultantStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ConsultantStatus[] | Prisma.ListEnumConsultantStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsultantStatus[] | Prisma.ListEnumConsultantStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsultantStatusFilter<$PrismaModel> | $Enums.ConsultantStatus
}

export type DecimalFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type IntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type SortOrderInput = {
  sort: Prisma.SortOrder
  nulls?: Prisma.NullsOrder
}

export type EnumConsultantRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsultantRole | Prisma.EnumConsultantRoleFieldRefInput<$PrismaModel>
  in?: $Enums.ConsultantRole[] | Prisma.ListEnumConsultantRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsultantRole[] | Prisma.ListEnumConsultantRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsultantRoleWithAggregatesFilter<$PrismaModel> | $Enums.ConsultantRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumConsultantRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumConsultantRoleFilter<$PrismaModel>
}

export type StringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  mode?: Prisma.QueryMode
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type EnumConsultantStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsultantStatus | Prisma.EnumConsultantStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ConsultantStatus[] | Prisma.ListEnumConsultantStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsultantStatus[] | Prisma.ListEnumConsultantStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsultantStatusWithAggregatesFilter<$PrismaModel> | $Enums.ConsultantStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumConsultantStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumConsultantStatusFilter<$PrismaModel>
}

export type DecimalWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalWithAggregatesFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedDecimalFilter<$PrismaModel>
  _sum?: Prisma.NestedDecimalFilter<$PrismaModel>
  _min?: Prisma.NestedDecimalFilter<$PrismaModel>
  _max?: Prisma.NestedDecimalFilter<$PrismaModel>
}

export type IntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type EnumConsortiumTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsortiumType | Prisma.EnumConsortiumTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ConsortiumType[] | Prisma.ListEnumConsortiumTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsortiumType[] | Prisma.ListEnumConsortiumTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsortiumTypeFilter<$PrismaModel> | $Enums.ConsortiumType
}

export type EnumConsortiumStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsortiumStatus | Prisma.EnumConsortiumStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ConsortiumStatus[] | Prisma.ListEnumConsortiumStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsortiumStatus[] | Prisma.ListEnumConsortiumStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsortiumStatusFilter<$PrismaModel> | $Enums.ConsortiumStatus
}

export type EnumConsortiumTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsortiumType | Prisma.EnumConsortiumTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ConsortiumType[] | Prisma.ListEnumConsortiumTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsortiumType[] | Prisma.ListEnumConsortiumTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsortiumTypeWithAggregatesFilter<$PrismaModel> | $Enums.ConsortiumType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumConsortiumTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumConsortiumTypeFilter<$PrismaModel>
}

export type EnumConsortiumStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsortiumStatus | Prisma.EnumConsortiumStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ConsortiumStatus[] | Prisma.ListEnumConsortiumStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsortiumStatus[] | Prisma.ListEnumConsortiumStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsortiumStatusWithAggregatesFilter<$PrismaModel> | $Enums.ConsortiumStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumConsortiumStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumConsortiumStatusFilter<$PrismaModel>
}

export type EnumPipelineStageTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.PipelineStageType | Prisma.EnumPipelineStageTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PipelineStageType[] | Prisma.ListEnumPipelineStageTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PipelineStageType[] | Prisma.ListEnumPipelineStageTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPipelineStageTypeFilter<$PrismaModel> | $Enums.PipelineStageType
}

export type BoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type EnumPipelineStageTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PipelineStageType | Prisma.EnumPipelineStageTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PipelineStageType[] | Prisma.ListEnumPipelineStageTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PipelineStageType[] | Prisma.ListEnumPipelineStageTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPipelineStageTypeWithAggregatesFilter<$PrismaModel> | $Enums.PipelineStageType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPipelineStageTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPipelineStageTypeFilter<$PrismaModel>
}

export type BoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type EnumLeadSourceFilter<$PrismaModel = never> = {
  equals?: $Enums.LeadSource | Prisma.EnumLeadSourceFieldRefInput<$PrismaModel>
  in?: $Enums.LeadSource[] | Prisma.ListEnumLeadSourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.LeadSource[] | Prisma.ListEnumLeadSourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLeadSourceFilter<$PrismaModel> | $Enums.LeadSource
}

export type EnumLeadStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.LeadStatus | Prisma.EnumLeadStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LeadStatus[] | Prisma.ListEnumLeadStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LeadStatus[] | Prisma.ListEnumLeadStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLeadStatusFilter<$PrismaModel> | $Enums.LeadStatus
}

export type DateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type EnumLeadSourceWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LeadSource | Prisma.EnumLeadSourceFieldRefInput<$PrismaModel>
  in?: $Enums.LeadSource[] | Prisma.ListEnumLeadSourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.LeadSource[] | Prisma.ListEnumLeadSourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLeadSourceWithAggregatesFilter<$PrismaModel> | $Enums.LeadSource
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLeadSourceFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLeadSourceFilter<$PrismaModel>
}

export type EnumLeadStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LeadStatus | Prisma.EnumLeadStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LeadStatus[] | Prisma.ListEnumLeadStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LeadStatus[] | Prisma.ListEnumLeadStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLeadStatusWithAggregatesFilter<$PrismaModel> | $Enums.LeadStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLeadStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLeadStatusFilter<$PrismaModel>
}

export type DateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type EnumPersonTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.PersonType | Prisma.EnumPersonTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PersonType[] | Prisma.ListEnumPersonTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PersonType[] | Prisma.ListEnumPersonTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPersonTypeFilter<$PrismaModel> | $Enums.PersonType
}

export type EnumClientStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ClientStatus | Prisma.EnumClientStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ClientStatus[] | Prisma.ListEnumClientStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ClientStatus[] | Prisma.ListEnumClientStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumClientStatusFilter<$PrismaModel> | $Enums.ClientStatus
}

export type EnumPersonTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PersonType | Prisma.EnumPersonTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PersonType[] | Prisma.ListEnumPersonTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PersonType[] | Prisma.ListEnumPersonTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPersonTypeWithAggregatesFilter<$PrismaModel> | $Enums.PersonType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPersonTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPersonTypeFilter<$PrismaModel>
}

export type EnumClientStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ClientStatus | Prisma.EnumClientStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ClientStatus[] | Prisma.ListEnumClientStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ClientStatus[] | Prisma.ListEnumClientStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumClientStatusWithAggregatesFilter<$PrismaModel> | $Enums.ClientStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumClientStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumClientStatusFilter<$PrismaModel>
}

export type EnumProposalStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ProposalStatus | Prisma.EnumProposalStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ProposalStatus[] | Prisma.ListEnumProposalStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ProposalStatus[] | Prisma.ListEnumProposalStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumProposalStatusFilter<$PrismaModel> | $Enums.ProposalStatus
}

export type EnumProposalStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ProposalStatus | Prisma.EnumProposalStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ProposalStatus[] | Prisma.ListEnumProposalStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ProposalStatus[] | Prisma.ListEnumProposalStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumProposalStatusWithAggregatesFilter<$PrismaModel> | $Enums.ProposalStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumProposalStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumProposalStatusFilter<$PrismaModel>
}

export type EnumMeetingTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingType | Prisma.EnumMeetingTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MeetingType[] | Prisma.ListEnumMeetingTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.MeetingType[] | Prisma.ListEnumMeetingTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMeetingTypeFilter<$PrismaModel> | $Enums.MeetingType
}

export type EnumMeetingStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingStatus | Prisma.EnumMeetingStatusFieldRefInput<$PrismaModel>
  in?: $Enums.MeetingStatus[] | Prisma.ListEnumMeetingStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.MeetingStatus[] | Prisma.ListEnumMeetingStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMeetingStatusFilter<$PrismaModel> | $Enums.MeetingStatus
}

export type EnumMeetingOutcomeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingOutcome | Prisma.EnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  in?: $Enums.MeetingOutcome[] | Prisma.ListEnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.MeetingOutcome[] | Prisma.ListEnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumMeetingOutcomeNullableFilter<$PrismaModel> | $Enums.MeetingOutcome | null
}

export type EnumMeetingTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingType | Prisma.EnumMeetingTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MeetingType[] | Prisma.ListEnumMeetingTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.MeetingType[] | Prisma.ListEnumMeetingTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMeetingTypeWithAggregatesFilter<$PrismaModel> | $Enums.MeetingType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMeetingTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMeetingTypeFilter<$PrismaModel>
}

export type EnumMeetingStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingStatus | Prisma.EnumMeetingStatusFieldRefInput<$PrismaModel>
  in?: $Enums.MeetingStatus[] | Prisma.ListEnumMeetingStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.MeetingStatus[] | Prisma.ListEnumMeetingStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMeetingStatusWithAggregatesFilter<$PrismaModel> | $Enums.MeetingStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMeetingStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMeetingStatusFilter<$PrismaModel>
}

export type EnumMeetingOutcomeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingOutcome | Prisma.EnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  in?: $Enums.MeetingOutcome[] | Prisma.ListEnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.MeetingOutcome[] | Prisma.ListEnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumMeetingOutcomeNullableWithAggregatesFilter<$PrismaModel> | $Enums.MeetingOutcome | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMeetingOutcomeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMeetingOutcomeNullableFilter<$PrismaModel>
}

export type EnumSaleStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.SaleStatus | Prisma.EnumSaleStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SaleStatus[] | Prisma.ListEnumSaleStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.SaleStatus[] | Prisma.ListEnumSaleStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSaleStatusFilter<$PrismaModel> | $Enums.SaleStatus
}

export type EnumQuotaStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.QuotaStatus | Prisma.EnumQuotaStatusFieldRefInput<$PrismaModel>
  in?: $Enums.QuotaStatus[] | Prisma.ListEnumQuotaStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.QuotaStatus[] | Prisma.ListEnumQuotaStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumQuotaStatusFilter<$PrismaModel> | $Enums.QuotaStatus
}

export type EnumPaymentMethodFilter<$PrismaModel = never> = {
  equals?: $Enums.PaymentMethod | Prisma.EnumPaymentMethodFieldRefInput<$PrismaModel>
  in?: $Enums.PaymentMethod[] | Prisma.ListEnumPaymentMethodFieldRefInput<$PrismaModel>
  notIn?: $Enums.PaymentMethod[] | Prisma.ListEnumPaymentMethodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPaymentMethodFilter<$PrismaModel> | $Enums.PaymentMethod
}

export type EnumSaleStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SaleStatus | Prisma.EnumSaleStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SaleStatus[] | Prisma.ListEnumSaleStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.SaleStatus[] | Prisma.ListEnumSaleStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSaleStatusWithAggregatesFilter<$PrismaModel> | $Enums.SaleStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSaleStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSaleStatusFilter<$PrismaModel>
}

export type EnumQuotaStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.QuotaStatus | Prisma.EnumQuotaStatusFieldRefInput<$PrismaModel>
  in?: $Enums.QuotaStatus[] | Prisma.ListEnumQuotaStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.QuotaStatus[] | Prisma.ListEnumQuotaStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumQuotaStatusWithAggregatesFilter<$PrismaModel> | $Enums.QuotaStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumQuotaStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumQuotaStatusFilter<$PrismaModel>
}

export type EnumPaymentMethodWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PaymentMethod | Prisma.EnumPaymentMethodFieldRefInput<$PrismaModel>
  in?: $Enums.PaymentMethod[] | Prisma.ListEnumPaymentMethodFieldRefInput<$PrismaModel>
  notIn?: $Enums.PaymentMethod[] | Prisma.ListEnumPaymentMethodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPaymentMethodWithAggregatesFilter<$PrismaModel> | $Enums.PaymentMethod
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPaymentMethodFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPaymentMethodFilter<$PrismaModel>
}

export type EnumTaskTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskType | Prisma.EnumTaskTypeFieldRefInput<$PrismaModel>
  in?: $Enums.TaskType[] | Prisma.ListEnumTaskTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskType[] | Prisma.ListEnumTaskTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskTypeFilter<$PrismaModel> | $Enums.TaskType
}

export type EnumTaskStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskStatus | Prisma.EnumTaskStatusFieldRefInput<$PrismaModel>
  in?: $Enums.TaskStatus[] | Prisma.ListEnumTaskStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskStatus[] | Prisma.ListEnumTaskStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskStatusFilter<$PrismaModel> | $Enums.TaskStatus
}

export type EnumTaskPriorityFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskPriority | Prisma.EnumTaskPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.TaskPriority[] | Prisma.ListEnumTaskPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskPriority[] | Prisma.ListEnumTaskPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskPriorityFilter<$PrismaModel> | $Enums.TaskPriority
}

export type EnumTaskTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskType | Prisma.EnumTaskTypeFieldRefInput<$PrismaModel>
  in?: $Enums.TaskType[] | Prisma.ListEnumTaskTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskType[] | Prisma.ListEnumTaskTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskTypeWithAggregatesFilter<$PrismaModel> | $Enums.TaskType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTaskTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTaskTypeFilter<$PrismaModel>
}

export type EnumTaskStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskStatus | Prisma.EnumTaskStatusFieldRefInput<$PrismaModel>
  in?: $Enums.TaskStatus[] | Prisma.ListEnumTaskStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskStatus[] | Prisma.ListEnumTaskStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskStatusWithAggregatesFilter<$PrismaModel> | $Enums.TaskStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTaskStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTaskStatusFilter<$PrismaModel>
}

export type EnumTaskPriorityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskPriority | Prisma.EnumTaskPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.TaskPriority[] | Prisma.ListEnumTaskPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskPriority[] | Prisma.ListEnumTaskPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskPriorityWithAggregatesFilter<$PrismaModel> | $Enums.TaskPriority
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTaskPriorityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTaskPriorityFilter<$PrismaModel>
}

export type EnumCommercialJourneyPriorityFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialJourneyPriority | Prisma.EnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialJourneyPriority[] | Prisma.ListEnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialJourneyPriority[] | Prisma.ListEnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialJourneyPriorityFilter<$PrismaModel> | $Enums.CommercialJourneyPriority
}

export type EnumCommercialJourneyOutcomeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialJourneyOutcome | Prisma.EnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  in?: $Enums.CommercialJourneyOutcome[] | Prisma.ListEnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.CommercialJourneyOutcome[] | Prisma.ListEnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumCommercialJourneyOutcomeNullableFilter<$PrismaModel> | $Enums.CommercialJourneyOutcome | null
}

export type EnumCommercialJourneyPriorityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialJourneyPriority | Prisma.EnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialJourneyPriority[] | Prisma.ListEnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialJourneyPriority[] | Prisma.ListEnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialJourneyPriorityWithAggregatesFilter<$PrismaModel> | $Enums.CommercialJourneyPriority
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialJourneyPriorityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialJourneyPriorityFilter<$PrismaModel>
}

export type EnumCommercialJourneyOutcomeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialJourneyOutcome | Prisma.EnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  in?: $Enums.CommercialJourneyOutcome[] | Prisma.ListEnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.CommercialJourneyOutcome[] | Prisma.ListEnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumCommercialJourneyOutcomeNullableWithAggregatesFilter<$PrismaModel> | $Enums.CommercialJourneyOutcome | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialJourneyOutcomeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialJourneyOutcomeNullableFilter<$PrismaModel>
}

export type EnumCommercialEventTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialEventType | Prisma.EnumCommercialEventTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialEventType[] | Prisma.ListEnumCommercialEventTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialEventType[] | Prisma.ListEnumCommercialEventTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialEventTypeFilter<$PrismaModel> | $Enums.CommercialEventType
}

export type EnumCommercialActorTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActorType | Prisma.EnumCommercialActorTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActorType[] | Prisma.ListEnumCommercialActorTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActorType[] | Prisma.ListEnumCommercialActorTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActorTypeFilter<$PrismaModel> | $Enums.CommercialActorType
}

export type JsonFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonFilterBase<$PrismaModel>>, 'path'>>

export type JsonFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type EnumCommercialEventTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialEventType | Prisma.EnumCommercialEventTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialEventType[] | Prisma.ListEnumCommercialEventTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialEventType[] | Prisma.ListEnumCommercialEventTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialEventTypeWithAggregatesFilter<$PrismaModel> | $Enums.CommercialEventType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialEventTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialEventTypeFilter<$PrismaModel>
}

export type EnumCommercialActorTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActorType | Prisma.EnumCommercialActorTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActorType[] | Prisma.ListEnumCommercialActorTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActorType[] | Prisma.ListEnumCommercialActorTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActorTypeWithAggregatesFilter<$PrismaModel> | $Enums.CommercialActorType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialActorTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialActorTypeFilter<$PrismaModel>
}

export type JsonWithAggregatesFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<JsonWithAggregatesFilterBase<$PrismaModel>>, Exclude<keyof Required<JsonWithAggregatesFilterBase<$PrismaModel>>, 'path'>>,
    Required<JsonWithAggregatesFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<JsonWithAggregatesFilterBase<$PrismaModel>>, 'path'>>

export type JsonWithAggregatesFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedJsonFilter<$PrismaModel>
  _max?: Prisma.NestedJsonFilter<$PrismaModel>
}

export type EnumCommercialActionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionType | Prisma.EnumCommercialActionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionType[] | Prisma.ListEnumCommercialActionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionType[] | Prisma.ListEnumCommercialActionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionTypeFilter<$PrismaModel> | $Enums.CommercialActionType
}

export type EnumCommercialActionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionStatus | Prisma.EnumCommercialActionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionStatus[] | Prisma.ListEnumCommercialActionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionStatus[] | Prisma.ListEnumCommercialActionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionStatusFilter<$PrismaModel> | $Enums.CommercialActionStatus
}

export type EnumCommercialActionOriginFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionOrigin | Prisma.EnumCommercialActionOriginFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionOrigin[] | Prisma.ListEnumCommercialActionOriginFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionOrigin[] | Prisma.ListEnumCommercialActionOriginFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionOriginFilter<$PrismaModel> | $Enums.CommercialActionOrigin
}

export type EnumCommercialActionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionType | Prisma.EnumCommercialActionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionType[] | Prisma.ListEnumCommercialActionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionType[] | Prisma.ListEnumCommercialActionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionTypeWithAggregatesFilter<$PrismaModel> | $Enums.CommercialActionType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialActionTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialActionTypeFilter<$PrismaModel>
}

export type EnumCommercialActionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionStatus | Prisma.EnumCommercialActionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionStatus[] | Prisma.ListEnumCommercialActionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionStatus[] | Prisma.ListEnumCommercialActionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionStatusWithAggregatesFilter<$PrismaModel> | $Enums.CommercialActionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialActionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialActionStatusFilter<$PrismaModel>
}

export type EnumCommercialActionOriginWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionOrigin | Prisma.EnumCommercialActionOriginFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionOrigin[] | Prisma.ListEnumCommercialActionOriginFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionOrigin[] | Prisma.ListEnumCommercialActionOriginFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionOriginWithAggregatesFilter<$PrismaModel> | $Enums.CommercialActionOrigin
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialActionOriginFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialActionOriginFilter<$PrismaModel>
}

export type EnumNextBestActionPriorityFilter<$PrismaModel = never> = {
  equals?: $Enums.NextBestActionPriority | Prisma.EnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.NextBestActionPriority[] | Prisma.ListEnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.NextBestActionPriority[] | Prisma.ListEnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumNextBestActionPriorityFilter<$PrismaModel> | $Enums.NextBestActionPriority
}

export type EnumNextBestActionSourceFilter<$PrismaModel = never> = {
  equals?: $Enums.NextBestActionSource | Prisma.EnumNextBestActionSourceFieldRefInput<$PrismaModel>
  in?: $Enums.NextBestActionSource[] | Prisma.ListEnumNextBestActionSourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.NextBestActionSource[] | Prisma.ListEnumNextBestActionSourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumNextBestActionSourceFilter<$PrismaModel> | $Enums.NextBestActionSource
}

export type EnumNextBestActionPriorityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.NextBestActionPriority | Prisma.EnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.NextBestActionPriority[] | Prisma.ListEnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.NextBestActionPriority[] | Prisma.ListEnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumNextBestActionPriorityWithAggregatesFilter<$PrismaModel> | $Enums.NextBestActionPriority
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumNextBestActionPriorityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumNextBestActionPriorityFilter<$PrismaModel>
}

export type EnumNextBestActionSourceWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.NextBestActionSource | Prisma.EnumNextBestActionSourceFieldRefInput<$PrismaModel>
  in?: $Enums.NextBestActionSource[] | Prisma.ListEnumNextBestActionSourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.NextBestActionSource[] | Prisma.ListEnumNextBestActionSourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumNextBestActionSourceWithAggregatesFilter<$PrismaModel> | $Enums.NextBestActionSource
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumNextBestActionSourceFilter<$PrismaModel>
  _max?: Prisma.NestedEnumNextBestActionSourceFilter<$PrismaModel>
}

export type NestedStringFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringFilter<$PrismaModel> | string
}

export type NestedEnumWorkspaceStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.WorkspaceStatus | Prisma.EnumWorkspaceStatusFieldRefInput<$PrismaModel>
  in?: $Enums.WorkspaceStatus[] | Prisma.ListEnumWorkspaceStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorkspaceStatus[] | Prisma.ListEnumWorkspaceStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorkspaceStatusFilter<$PrismaModel> | $Enums.WorkspaceStatus
}

export type NestedDateTimeFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeFilter<$PrismaModel> | Date | string
}

export type NestedStringWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel>
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel>
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringWithAggregatesFilter<$PrismaModel> | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedStringFilter<$PrismaModel>
  _max?: Prisma.NestedStringFilter<$PrismaModel>
}

export type NestedIntFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntFilter<$PrismaModel> | number
}

export type NestedEnumWorkspaceStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.WorkspaceStatus | Prisma.EnumWorkspaceStatusFieldRefInput<$PrismaModel>
  in?: $Enums.WorkspaceStatus[] | Prisma.ListEnumWorkspaceStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.WorkspaceStatus[] | Prisma.ListEnumWorkspaceStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumWorkspaceStatusWithAggregatesFilter<$PrismaModel> | $Enums.WorkspaceStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumWorkspaceStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumWorkspaceStatusFilter<$PrismaModel>
}

export type NestedDateTimeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel>
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeWithAggregatesFilter<$PrismaModel> | Date | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeFilter<$PrismaModel>
}

export type NestedEnumConsultantRoleFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsultantRole | Prisma.EnumConsultantRoleFieldRefInput<$PrismaModel>
  in?: $Enums.ConsultantRole[] | Prisma.ListEnumConsultantRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsultantRole[] | Prisma.ListEnumConsultantRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsultantRoleFilter<$PrismaModel> | $Enums.ConsultantRole
}

export type NestedStringNullableFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableFilter<$PrismaModel> | string | null
}

export type NestedEnumConsultantStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsultantStatus | Prisma.EnumConsultantStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ConsultantStatus[] | Prisma.ListEnumConsultantStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsultantStatus[] | Prisma.ListEnumConsultantStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsultantStatusFilter<$PrismaModel> | $Enums.ConsultantStatus
}

export type NestedDecimalFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string
}

export type NestedEnumConsultantRoleWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsultantRole | Prisma.EnumConsultantRoleFieldRefInput<$PrismaModel>
  in?: $Enums.ConsultantRole[] | Prisma.ListEnumConsultantRoleFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsultantRole[] | Prisma.ListEnumConsultantRoleFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsultantRoleWithAggregatesFilter<$PrismaModel> | $Enums.ConsultantRole
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumConsultantRoleFilter<$PrismaModel>
  _max?: Prisma.NestedEnumConsultantRoleFilter<$PrismaModel>
}

export type NestedStringNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: string | Prisma.StringFieldRefInput<$PrismaModel> | null
  in?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  notIn?: string[] | Prisma.ListStringFieldRefInput<$PrismaModel> | null
  lt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  lte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gt?: string | Prisma.StringFieldRefInput<$PrismaModel>
  gte?: string | Prisma.StringFieldRefInput<$PrismaModel>
  contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  startsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  endsWith?: string | Prisma.StringFieldRefInput<$PrismaModel>
  not?: Prisma.NestedStringNullableWithAggregatesFilter<$PrismaModel> | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedStringNullableFilter<$PrismaModel>
  _max?: Prisma.NestedStringNullableFilter<$PrismaModel>
}

export type NestedIntNullableFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel> | null
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel> | null
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntNullableFilter<$PrismaModel> | number | null
}

export type NestedEnumConsultantStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsultantStatus | Prisma.EnumConsultantStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ConsultantStatus[] | Prisma.ListEnumConsultantStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsultantStatus[] | Prisma.ListEnumConsultantStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsultantStatusWithAggregatesFilter<$PrismaModel> | $Enums.ConsultantStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumConsultantStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumConsultantStatusFilter<$PrismaModel>
}

export type NestedDecimalWithAggregatesFilter<$PrismaModel = never> = {
  equals?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  in?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  notIn?: runtime.Decimal[] | runtime.DecimalJsLike[] | number[] | string[] | Prisma.ListDecimalFieldRefInput<$PrismaModel>
  lt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  lte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gt?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  gte?: runtime.Decimal | runtime.DecimalJsLike | number | string | Prisma.DecimalFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDecimalWithAggregatesFilter<$PrismaModel> | runtime.Decimal | runtime.DecimalJsLike | number | string
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedDecimalFilter<$PrismaModel>
  _sum?: Prisma.NestedDecimalFilter<$PrismaModel>
  _min?: Prisma.NestedDecimalFilter<$PrismaModel>
  _max?: Prisma.NestedDecimalFilter<$PrismaModel>
}

export type NestedIntWithAggregatesFilter<$PrismaModel = never> = {
  equals?: number | Prisma.IntFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListIntFieldRefInput<$PrismaModel>
  lt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  lte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gt?: number | Prisma.IntFieldRefInput<$PrismaModel>
  gte?: number | Prisma.IntFieldRefInput<$PrismaModel>
  not?: Prisma.NestedIntWithAggregatesFilter<$PrismaModel> | number
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _avg?: Prisma.NestedFloatFilter<$PrismaModel>
  _sum?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedIntFilter<$PrismaModel>
  _max?: Prisma.NestedIntFilter<$PrismaModel>
}

export type NestedFloatFilter<$PrismaModel = never> = {
  equals?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  in?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  notIn?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  lt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  lte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gt?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  gte?: number | Prisma.FloatFieldRefInput<$PrismaModel>
  not?: Prisma.NestedFloatFilter<$PrismaModel> | number
}

export type NestedEnumConsortiumTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsortiumType | Prisma.EnumConsortiumTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ConsortiumType[] | Prisma.ListEnumConsortiumTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsortiumType[] | Prisma.ListEnumConsortiumTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsortiumTypeFilter<$PrismaModel> | $Enums.ConsortiumType
}

export type NestedEnumConsortiumStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsortiumStatus | Prisma.EnumConsortiumStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ConsortiumStatus[] | Prisma.ListEnumConsortiumStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsortiumStatus[] | Prisma.ListEnumConsortiumStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsortiumStatusFilter<$PrismaModel> | $Enums.ConsortiumStatus
}

export type NestedEnumConsortiumTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsortiumType | Prisma.EnumConsortiumTypeFieldRefInput<$PrismaModel>
  in?: $Enums.ConsortiumType[] | Prisma.ListEnumConsortiumTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsortiumType[] | Prisma.ListEnumConsortiumTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsortiumTypeWithAggregatesFilter<$PrismaModel> | $Enums.ConsortiumType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumConsortiumTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumConsortiumTypeFilter<$PrismaModel>
}

export type NestedEnumConsortiumStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ConsortiumStatus | Prisma.EnumConsortiumStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ConsortiumStatus[] | Prisma.ListEnumConsortiumStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ConsortiumStatus[] | Prisma.ListEnumConsortiumStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumConsortiumStatusWithAggregatesFilter<$PrismaModel> | $Enums.ConsortiumStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumConsortiumStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumConsortiumStatusFilter<$PrismaModel>
}

export type NestedEnumPipelineStageTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.PipelineStageType | Prisma.EnumPipelineStageTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PipelineStageType[] | Prisma.ListEnumPipelineStageTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PipelineStageType[] | Prisma.ListEnumPipelineStageTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPipelineStageTypeFilter<$PrismaModel> | $Enums.PipelineStageType
}

export type NestedBoolFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolFilter<$PrismaModel> | boolean
}

export type NestedEnumPipelineStageTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PipelineStageType | Prisma.EnumPipelineStageTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PipelineStageType[] | Prisma.ListEnumPipelineStageTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PipelineStageType[] | Prisma.ListEnumPipelineStageTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPipelineStageTypeWithAggregatesFilter<$PrismaModel> | $Enums.PipelineStageType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPipelineStageTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPipelineStageTypeFilter<$PrismaModel>
}

export type NestedBoolWithAggregatesFilter<$PrismaModel = never> = {
  equals?: boolean | Prisma.BooleanFieldRefInput<$PrismaModel>
  not?: Prisma.NestedBoolWithAggregatesFilter<$PrismaModel> | boolean
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedBoolFilter<$PrismaModel>
  _max?: Prisma.NestedBoolFilter<$PrismaModel>
}

export type NestedEnumLeadSourceFilter<$PrismaModel = never> = {
  equals?: $Enums.LeadSource | Prisma.EnumLeadSourceFieldRefInput<$PrismaModel>
  in?: $Enums.LeadSource[] | Prisma.ListEnumLeadSourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.LeadSource[] | Prisma.ListEnumLeadSourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLeadSourceFilter<$PrismaModel> | $Enums.LeadSource
}

export type NestedEnumLeadStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.LeadStatus | Prisma.EnumLeadStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LeadStatus[] | Prisma.ListEnumLeadStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LeadStatus[] | Prisma.ListEnumLeadStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLeadStatusFilter<$PrismaModel> | $Enums.LeadStatus
}

export type NestedDateTimeNullableFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableFilter<$PrismaModel> | Date | string | null
}

export type NestedEnumLeadSourceWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LeadSource | Prisma.EnumLeadSourceFieldRefInput<$PrismaModel>
  in?: $Enums.LeadSource[] | Prisma.ListEnumLeadSourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.LeadSource[] | Prisma.ListEnumLeadSourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLeadSourceWithAggregatesFilter<$PrismaModel> | $Enums.LeadSource
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLeadSourceFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLeadSourceFilter<$PrismaModel>
}

export type NestedEnumLeadStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.LeadStatus | Prisma.EnumLeadStatusFieldRefInput<$PrismaModel>
  in?: $Enums.LeadStatus[] | Prisma.ListEnumLeadStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.LeadStatus[] | Prisma.ListEnumLeadStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumLeadStatusWithAggregatesFilter<$PrismaModel> | $Enums.LeadStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumLeadStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumLeadStatusFilter<$PrismaModel>
}

export type NestedDateTimeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel> | null
  in?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  notIn?: Date[] | string[] | Prisma.ListDateTimeFieldRefInput<$PrismaModel> | null
  lt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  lte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gt?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  gte?: Date | string | Prisma.DateTimeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedDateTimeNullableWithAggregatesFilter<$PrismaModel> | Date | string | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedDateTimeNullableFilter<$PrismaModel>
}

export type NestedEnumPersonTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.PersonType | Prisma.EnumPersonTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PersonType[] | Prisma.ListEnumPersonTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PersonType[] | Prisma.ListEnumPersonTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPersonTypeFilter<$PrismaModel> | $Enums.PersonType
}

export type NestedEnumClientStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ClientStatus | Prisma.EnumClientStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ClientStatus[] | Prisma.ListEnumClientStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ClientStatus[] | Prisma.ListEnumClientStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumClientStatusFilter<$PrismaModel> | $Enums.ClientStatus
}

export type NestedEnumPersonTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PersonType | Prisma.EnumPersonTypeFieldRefInput<$PrismaModel>
  in?: $Enums.PersonType[] | Prisma.ListEnumPersonTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.PersonType[] | Prisma.ListEnumPersonTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPersonTypeWithAggregatesFilter<$PrismaModel> | $Enums.PersonType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPersonTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPersonTypeFilter<$PrismaModel>
}

export type NestedEnumClientStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ClientStatus | Prisma.EnumClientStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ClientStatus[] | Prisma.ListEnumClientStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ClientStatus[] | Prisma.ListEnumClientStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumClientStatusWithAggregatesFilter<$PrismaModel> | $Enums.ClientStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumClientStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumClientStatusFilter<$PrismaModel>
}

export type NestedEnumProposalStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.ProposalStatus | Prisma.EnumProposalStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ProposalStatus[] | Prisma.ListEnumProposalStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ProposalStatus[] | Prisma.ListEnumProposalStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumProposalStatusFilter<$PrismaModel> | $Enums.ProposalStatus
}

export type NestedEnumProposalStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.ProposalStatus | Prisma.EnumProposalStatusFieldRefInput<$PrismaModel>
  in?: $Enums.ProposalStatus[] | Prisma.ListEnumProposalStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.ProposalStatus[] | Prisma.ListEnumProposalStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumProposalStatusWithAggregatesFilter<$PrismaModel> | $Enums.ProposalStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumProposalStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumProposalStatusFilter<$PrismaModel>
}

export type NestedEnumMeetingTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingType | Prisma.EnumMeetingTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MeetingType[] | Prisma.ListEnumMeetingTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.MeetingType[] | Prisma.ListEnumMeetingTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMeetingTypeFilter<$PrismaModel> | $Enums.MeetingType
}

export type NestedEnumMeetingStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingStatus | Prisma.EnumMeetingStatusFieldRefInput<$PrismaModel>
  in?: $Enums.MeetingStatus[] | Prisma.ListEnumMeetingStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.MeetingStatus[] | Prisma.ListEnumMeetingStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMeetingStatusFilter<$PrismaModel> | $Enums.MeetingStatus
}

export type NestedEnumMeetingOutcomeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingOutcome | Prisma.EnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  in?: $Enums.MeetingOutcome[] | Prisma.ListEnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.MeetingOutcome[] | Prisma.ListEnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumMeetingOutcomeNullableFilter<$PrismaModel> | $Enums.MeetingOutcome | null
}

export type NestedEnumMeetingTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingType | Prisma.EnumMeetingTypeFieldRefInput<$PrismaModel>
  in?: $Enums.MeetingType[] | Prisma.ListEnumMeetingTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.MeetingType[] | Prisma.ListEnumMeetingTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMeetingTypeWithAggregatesFilter<$PrismaModel> | $Enums.MeetingType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMeetingTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMeetingTypeFilter<$PrismaModel>
}

export type NestedEnumMeetingStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingStatus | Prisma.EnumMeetingStatusFieldRefInput<$PrismaModel>
  in?: $Enums.MeetingStatus[] | Prisma.ListEnumMeetingStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.MeetingStatus[] | Prisma.ListEnumMeetingStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumMeetingStatusWithAggregatesFilter<$PrismaModel> | $Enums.MeetingStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMeetingStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMeetingStatusFilter<$PrismaModel>
}

export type NestedEnumMeetingOutcomeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.MeetingOutcome | Prisma.EnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  in?: $Enums.MeetingOutcome[] | Prisma.ListEnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.MeetingOutcome[] | Prisma.ListEnumMeetingOutcomeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumMeetingOutcomeNullableWithAggregatesFilter<$PrismaModel> | $Enums.MeetingOutcome | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumMeetingOutcomeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumMeetingOutcomeNullableFilter<$PrismaModel>
}

export type NestedEnumSaleStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.SaleStatus | Prisma.EnumSaleStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SaleStatus[] | Prisma.ListEnumSaleStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.SaleStatus[] | Prisma.ListEnumSaleStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSaleStatusFilter<$PrismaModel> | $Enums.SaleStatus
}

export type NestedEnumQuotaStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.QuotaStatus | Prisma.EnumQuotaStatusFieldRefInput<$PrismaModel>
  in?: $Enums.QuotaStatus[] | Prisma.ListEnumQuotaStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.QuotaStatus[] | Prisma.ListEnumQuotaStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumQuotaStatusFilter<$PrismaModel> | $Enums.QuotaStatus
}

export type NestedEnumPaymentMethodFilter<$PrismaModel = never> = {
  equals?: $Enums.PaymentMethod | Prisma.EnumPaymentMethodFieldRefInput<$PrismaModel>
  in?: $Enums.PaymentMethod[] | Prisma.ListEnumPaymentMethodFieldRefInput<$PrismaModel>
  notIn?: $Enums.PaymentMethod[] | Prisma.ListEnumPaymentMethodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPaymentMethodFilter<$PrismaModel> | $Enums.PaymentMethod
}

export type NestedEnumSaleStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.SaleStatus | Prisma.EnumSaleStatusFieldRefInput<$PrismaModel>
  in?: $Enums.SaleStatus[] | Prisma.ListEnumSaleStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.SaleStatus[] | Prisma.ListEnumSaleStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumSaleStatusWithAggregatesFilter<$PrismaModel> | $Enums.SaleStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumSaleStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumSaleStatusFilter<$PrismaModel>
}

export type NestedEnumQuotaStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.QuotaStatus | Prisma.EnumQuotaStatusFieldRefInput<$PrismaModel>
  in?: $Enums.QuotaStatus[] | Prisma.ListEnumQuotaStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.QuotaStatus[] | Prisma.ListEnumQuotaStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumQuotaStatusWithAggregatesFilter<$PrismaModel> | $Enums.QuotaStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumQuotaStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumQuotaStatusFilter<$PrismaModel>
}

export type NestedEnumPaymentMethodWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.PaymentMethod | Prisma.EnumPaymentMethodFieldRefInput<$PrismaModel>
  in?: $Enums.PaymentMethod[] | Prisma.ListEnumPaymentMethodFieldRefInput<$PrismaModel>
  notIn?: $Enums.PaymentMethod[] | Prisma.ListEnumPaymentMethodFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumPaymentMethodWithAggregatesFilter<$PrismaModel> | $Enums.PaymentMethod
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumPaymentMethodFilter<$PrismaModel>
  _max?: Prisma.NestedEnumPaymentMethodFilter<$PrismaModel>
}

export type NestedEnumTaskTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskType | Prisma.EnumTaskTypeFieldRefInput<$PrismaModel>
  in?: $Enums.TaskType[] | Prisma.ListEnumTaskTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskType[] | Prisma.ListEnumTaskTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskTypeFilter<$PrismaModel> | $Enums.TaskType
}

export type NestedEnumTaskStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskStatus | Prisma.EnumTaskStatusFieldRefInput<$PrismaModel>
  in?: $Enums.TaskStatus[] | Prisma.ListEnumTaskStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskStatus[] | Prisma.ListEnumTaskStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskStatusFilter<$PrismaModel> | $Enums.TaskStatus
}

export type NestedEnumTaskPriorityFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskPriority | Prisma.EnumTaskPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.TaskPriority[] | Prisma.ListEnumTaskPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskPriority[] | Prisma.ListEnumTaskPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskPriorityFilter<$PrismaModel> | $Enums.TaskPriority
}

export type NestedEnumTaskTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskType | Prisma.EnumTaskTypeFieldRefInput<$PrismaModel>
  in?: $Enums.TaskType[] | Prisma.ListEnumTaskTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskType[] | Prisma.ListEnumTaskTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskTypeWithAggregatesFilter<$PrismaModel> | $Enums.TaskType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTaskTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTaskTypeFilter<$PrismaModel>
}

export type NestedEnumTaskStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskStatus | Prisma.EnumTaskStatusFieldRefInput<$PrismaModel>
  in?: $Enums.TaskStatus[] | Prisma.ListEnumTaskStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskStatus[] | Prisma.ListEnumTaskStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskStatusWithAggregatesFilter<$PrismaModel> | $Enums.TaskStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTaskStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTaskStatusFilter<$PrismaModel>
}

export type NestedEnumTaskPriorityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.TaskPriority | Prisma.EnumTaskPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.TaskPriority[] | Prisma.ListEnumTaskPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.TaskPriority[] | Prisma.ListEnumTaskPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumTaskPriorityWithAggregatesFilter<$PrismaModel> | $Enums.TaskPriority
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumTaskPriorityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumTaskPriorityFilter<$PrismaModel>
}

export type NestedEnumCommercialJourneyPriorityFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialJourneyPriority | Prisma.EnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialJourneyPriority[] | Prisma.ListEnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialJourneyPriority[] | Prisma.ListEnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialJourneyPriorityFilter<$PrismaModel> | $Enums.CommercialJourneyPriority
}

export type NestedEnumCommercialJourneyOutcomeNullableFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialJourneyOutcome | Prisma.EnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  in?: $Enums.CommercialJourneyOutcome[] | Prisma.ListEnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.CommercialJourneyOutcome[] | Prisma.ListEnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumCommercialJourneyOutcomeNullableFilter<$PrismaModel> | $Enums.CommercialJourneyOutcome | null
}

export type NestedEnumCommercialJourneyPriorityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialJourneyPriority | Prisma.EnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialJourneyPriority[] | Prisma.ListEnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialJourneyPriority[] | Prisma.ListEnumCommercialJourneyPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialJourneyPriorityWithAggregatesFilter<$PrismaModel> | $Enums.CommercialJourneyPriority
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialJourneyPriorityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialJourneyPriorityFilter<$PrismaModel>
}

export type NestedEnumCommercialJourneyOutcomeNullableWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialJourneyOutcome | Prisma.EnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  in?: $Enums.CommercialJourneyOutcome[] | Prisma.ListEnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  notIn?: $Enums.CommercialJourneyOutcome[] | Prisma.ListEnumCommercialJourneyOutcomeFieldRefInput<$PrismaModel> | null
  not?: Prisma.NestedEnumCommercialJourneyOutcomeNullableWithAggregatesFilter<$PrismaModel> | $Enums.CommercialJourneyOutcome | null
  _count?: Prisma.NestedIntNullableFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialJourneyOutcomeNullableFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialJourneyOutcomeNullableFilter<$PrismaModel>
}

export type NestedEnumCommercialEventTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialEventType | Prisma.EnumCommercialEventTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialEventType[] | Prisma.ListEnumCommercialEventTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialEventType[] | Prisma.ListEnumCommercialEventTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialEventTypeFilter<$PrismaModel> | $Enums.CommercialEventType
}

export type NestedEnumCommercialActorTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActorType | Prisma.EnumCommercialActorTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActorType[] | Prisma.ListEnumCommercialActorTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActorType[] | Prisma.ListEnumCommercialActorTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActorTypeFilter<$PrismaModel> | $Enums.CommercialActorType
}

export type NestedEnumCommercialEventTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialEventType | Prisma.EnumCommercialEventTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialEventType[] | Prisma.ListEnumCommercialEventTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialEventType[] | Prisma.ListEnumCommercialEventTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialEventTypeWithAggregatesFilter<$PrismaModel> | $Enums.CommercialEventType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialEventTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialEventTypeFilter<$PrismaModel>
}

export type NestedEnumCommercialActorTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActorType | Prisma.EnumCommercialActorTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActorType[] | Prisma.ListEnumCommercialActorTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActorType[] | Prisma.ListEnumCommercialActorTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActorTypeWithAggregatesFilter<$PrismaModel> | $Enums.CommercialActorType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialActorTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialActorTypeFilter<$PrismaModel>
}

export type NestedJsonFilter<$PrismaModel = never> =
| Prisma.PatchUndefined<
    Prisma.Either<Required<NestedJsonFilterBase<$PrismaModel>>, Exclude<keyof Required<NestedJsonFilterBase<$PrismaModel>>, 'path'>>,
    Required<NestedJsonFilterBase<$PrismaModel>>
  >
| Prisma.OptionalFlat<Omit<Required<NestedJsonFilterBase<$PrismaModel>>, 'path'>>

export type NestedJsonFilterBase<$PrismaModel = never> = {
  equals?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
  path?: string[]
  mode?: Prisma.QueryMode | Prisma.EnumQueryModeFieldRefInput<$PrismaModel>
  string_contains?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_starts_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  string_ends_with?: string | Prisma.StringFieldRefInput<$PrismaModel>
  array_starts_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_ends_with?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  array_contains?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | null
  lt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  lte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gt?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  gte?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel>
  not?: runtime.InputJsonValue | Prisma.JsonFieldRefInput<$PrismaModel> | Prisma.JsonNullValueFilter
}

export type NestedEnumCommercialActionTypeFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionType | Prisma.EnumCommercialActionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionType[] | Prisma.ListEnumCommercialActionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionType[] | Prisma.ListEnumCommercialActionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionTypeFilter<$PrismaModel> | $Enums.CommercialActionType
}

export type NestedEnumCommercialActionStatusFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionStatus | Prisma.EnumCommercialActionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionStatus[] | Prisma.ListEnumCommercialActionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionStatus[] | Prisma.ListEnumCommercialActionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionStatusFilter<$PrismaModel> | $Enums.CommercialActionStatus
}

export type NestedEnumCommercialActionOriginFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionOrigin | Prisma.EnumCommercialActionOriginFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionOrigin[] | Prisma.ListEnumCommercialActionOriginFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionOrigin[] | Prisma.ListEnumCommercialActionOriginFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionOriginFilter<$PrismaModel> | $Enums.CommercialActionOrigin
}

export type NestedEnumCommercialActionTypeWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionType | Prisma.EnumCommercialActionTypeFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionType[] | Prisma.ListEnumCommercialActionTypeFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionType[] | Prisma.ListEnumCommercialActionTypeFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionTypeWithAggregatesFilter<$PrismaModel> | $Enums.CommercialActionType
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialActionTypeFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialActionTypeFilter<$PrismaModel>
}

export type NestedEnumCommercialActionStatusWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionStatus | Prisma.EnumCommercialActionStatusFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionStatus[] | Prisma.ListEnumCommercialActionStatusFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionStatus[] | Prisma.ListEnumCommercialActionStatusFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionStatusWithAggregatesFilter<$PrismaModel> | $Enums.CommercialActionStatus
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialActionStatusFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialActionStatusFilter<$PrismaModel>
}

export type NestedEnumCommercialActionOriginWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.CommercialActionOrigin | Prisma.EnumCommercialActionOriginFieldRefInput<$PrismaModel>
  in?: $Enums.CommercialActionOrigin[] | Prisma.ListEnumCommercialActionOriginFieldRefInput<$PrismaModel>
  notIn?: $Enums.CommercialActionOrigin[] | Prisma.ListEnumCommercialActionOriginFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumCommercialActionOriginWithAggregatesFilter<$PrismaModel> | $Enums.CommercialActionOrigin
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumCommercialActionOriginFilter<$PrismaModel>
  _max?: Prisma.NestedEnumCommercialActionOriginFilter<$PrismaModel>
}

export type NestedEnumNextBestActionPriorityFilter<$PrismaModel = never> = {
  equals?: $Enums.NextBestActionPriority | Prisma.EnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.NextBestActionPriority[] | Prisma.ListEnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.NextBestActionPriority[] | Prisma.ListEnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumNextBestActionPriorityFilter<$PrismaModel> | $Enums.NextBestActionPriority
}

export type NestedEnumNextBestActionSourceFilter<$PrismaModel = never> = {
  equals?: $Enums.NextBestActionSource | Prisma.EnumNextBestActionSourceFieldRefInput<$PrismaModel>
  in?: $Enums.NextBestActionSource[] | Prisma.ListEnumNextBestActionSourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.NextBestActionSource[] | Prisma.ListEnumNextBestActionSourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumNextBestActionSourceFilter<$PrismaModel> | $Enums.NextBestActionSource
}

export type NestedEnumNextBestActionPriorityWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.NextBestActionPriority | Prisma.EnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  in?: $Enums.NextBestActionPriority[] | Prisma.ListEnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  notIn?: $Enums.NextBestActionPriority[] | Prisma.ListEnumNextBestActionPriorityFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumNextBestActionPriorityWithAggregatesFilter<$PrismaModel> | $Enums.NextBestActionPriority
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumNextBestActionPriorityFilter<$PrismaModel>
  _max?: Prisma.NestedEnumNextBestActionPriorityFilter<$PrismaModel>
}

export type NestedEnumNextBestActionSourceWithAggregatesFilter<$PrismaModel = never> = {
  equals?: $Enums.NextBestActionSource | Prisma.EnumNextBestActionSourceFieldRefInput<$PrismaModel>
  in?: $Enums.NextBestActionSource[] | Prisma.ListEnumNextBestActionSourceFieldRefInput<$PrismaModel>
  notIn?: $Enums.NextBestActionSource[] | Prisma.ListEnumNextBestActionSourceFieldRefInput<$PrismaModel>
  not?: Prisma.NestedEnumNextBestActionSourceWithAggregatesFilter<$PrismaModel> | $Enums.NextBestActionSource
  _count?: Prisma.NestedIntFilter<$PrismaModel>
  _min?: Prisma.NestedEnumNextBestActionSourceFilter<$PrismaModel>
  _max?: Prisma.NestedEnumNextBestActionSourceFilter<$PrismaModel>
}


