
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  Workspace: 'Workspace',
  Consultant: 'Consultant',
  Consortium: 'Consortium',
  PipelineStage: 'PipelineStage',
  Lead: 'Lead',
  Client: 'Client',
  Proposal: 'Proposal',
  Meeting: 'Meeting',
  Sale: 'Sale',
  Task: 'Task',
  JourneyPhase: 'JourneyPhase',
  JourneyState: 'JourneyState',
  CommercialJourney: 'CommercialJourney',
  CommercialEvent: 'CommercialEvent',
  CommercialAction: 'CommercialAction',
  WorkflowRule: 'WorkflowRule',
  NextBestAction: 'NextBestAction'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const WorkspaceScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkspaceScalarFieldEnum = (typeof WorkspaceScalarFieldEnum)[keyof typeof WorkspaceScalarFieldEnum]


export const ConsultantScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  name: 'name',
  email: 'email',
  phone: 'phone',
  document: 'document',
  role: 'role',
  team: 'team',
  region: 'region',
  avatarUrl: 'avatarUrl',
  status: 'status',
  monthlySalesTarget: 'monthlySalesTarget',
  monthlyLeadsTarget: 'monthlyLeadsTarget',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ConsultantScalarFieldEnum = (typeof ConsultantScalarFieldEnum)[keyof typeof ConsultantScalarFieldEnum]


export const ConsortiumScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  name: 'name',
  administrator: 'administrator',
  type: 'type',
  groupNumber: 'groupNumber',
  minCreditValue: 'minCreditValue',
  maxCreditValue: 'maxCreditValue',
  defaultTermMonths: 'defaultTermMonths',
  administrationFeePercent: 'administrationFeePercent',
  reserveFundPercent: 'reserveFundPercent',
  totalQuotas: 'totalQuotas',
  availableQuotas: 'availableQuotas',
  status: 'status',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ConsortiumScalarFieldEnum = (typeof ConsortiumScalarFieldEnum)[keyof typeof ConsortiumScalarFieldEnum]


export const PipelineStageScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  name: 'name',
  order: 'order',
  type: 'type',
  color: 'color',
  description: 'description',
  winProbability: 'winProbability',
  isClosedStage: 'isClosedStage',
  isWonStage: 'isWonStage',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type PipelineStageScalarFieldEnum = (typeof PipelineStageScalarFieldEnum)[keyof typeof PipelineStageScalarFieldEnum]


export const LeadScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  name: 'name',
  email: 'email',
  phone: 'phone',
  document: 'document',
  companyName: 'companyName',
  source: 'source',
  status: 'status',
  consortiumType: 'consortiumType',
  desiredCreditValue: 'desiredCreditValue',
  desiredTermMonths: 'desiredTermMonths',
  consultantId: 'consultantId',
  pipelineStageId: 'pipelineStageId',
  score: 'score',
  lostReason: 'lostReason',
  notes: 'notes',
  convertedClientId: 'convertedClientId',
  lastContactAt: 'lastContactAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type LeadScalarFieldEnum = (typeof LeadScalarFieldEnum)[keyof typeof LeadScalarFieldEnum]


export const ClientScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  type: 'type',
  name: 'name',
  email: 'email',
  phone: 'phone',
  document: 'document',
  birthDate: 'birthDate',
  companyName: 'companyName',
  tradeName: 'tradeName',
  stateRegistration: 'stateRegistration',
  addressStreet: 'addressStreet',
  addressNumber: 'addressNumber',
  addressComplement: 'addressComplement',
  addressNeighborhood: 'addressNeighborhood',
  addressCity: 'addressCity',
  addressState: 'addressState',
  addressZipCode: 'addressZipCode',
  consultantId: 'consultantId',
  status: 'status',
  tags: 'tags',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ClientScalarFieldEnum = (typeof ClientScalarFieldEnum)[keyof typeof ClientScalarFieldEnum]


export const ProposalScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  code: 'code',
  clientId: 'clientId',
  leadId: 'leadId',
  consultantId: 'consultantId',
  consortiumId: 'consortiumId',
  creditValue: 'creditValue',
  installmentValue: 'installmentValue',
  termMonths: 'termMonths',
  administrationFeePercent: 'administrationFeePercent',
  reserveFundPercent: 'reserveFundPercent',
  status: 'status',
  sentAt: 'sentAt',
  validUntil: 'validUntil',
  acceptedAt: 'acceptedAt',
  rejectedAt: 'rejectedAt',
  rejectionReason: 'rejectionReason',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type ProposalScalarFieldEnum = (typeof ProposalScalarFieldEnum)[keyof typeof ProposalScalarFieldEnum]


export const MeetingScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  startAt: 'startAt',
  endAt: 'endAt',
  location: 'location',
  meetingUrl: 'meetingUrl',
  consultantId: 'consultantId',
  leadId: 'leadId',
  clientId: 'clientId',
  proposalId: 'proposalId',
  outcome: 'outcome',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type MeetingScalarFieldEnum = (typeof MeetingScalarFieldEnum)[keyof typeof MeetingScalarFieldEnum]


export const SaleScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  contractNumber: 'contractNumber',
  proposalId: 'proposalId',
  clientId: 'clientId',
  consultantId: 'consultantId',
  consortiumId: 'consortiumId',
  groupNumber: 'groupNumber',
  quotaNumber: 'quotaNumber',
  creditValue: 'creditValue',
  installmentValue: 'installmentValue',
  termMonths: 'termMonths',
  administrationFeePercent: 'administrationFeePercent',
  reserveFundPercent: 'reserveFundPercent',
  commissionValue: 'commissionValue',
  commissionPercent: 'commissionPercent',
  status: 'status',
  quotaStatus: 'quotaStatus',
  paymentMethod: 'paymentMethod',
  saleDate: 'saleDate',
  firstInstallmentDate: 'firstInstallmentDate',
  contemplatedAt: 'contemplatedAt',
  paidOffAt: 'paidOffAt',
  cancelledAt: 'cancelledAt',
  cancellationReason: 'cancellationReason',
  notes: 'notes',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type SaleScalarFieldEnum = (typeof SaleScalarFieldEnum)[keyof typeof SaleScalarFieldEnum]


export const TaskScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  title: 'title',
  description: 'description',
  type: 'type',
  status: 'status',
  priority: 'priority',
  dueAt: 'dueAt',
  assignedToId: 'assignedToId',
  leadId: 'leadId',
  clientId: 'clientId',
  meetingId: 'meetingId',
  proposalId: 'proposalId',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type TaskScalarFieldEnum = (typeof TaskScalarFieldEnum)[keyof typeof TaskScalarFieldEnum]


export const JourneyPhaseScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  code: 'code',
  name: 'name',
  description: 'description',
  order: 'order',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type JourneyPhaseScalarFieldEnum = (typeof JourneyPhaseScalarFieldEnum)[keyof typeof JourneyPhaseScalarFieldEnum]


export const JourneyStateScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  phaseId: 'phaseId',
  code: 'code',
  name: 'name',
  description: 'description',
  order: 'order',
  color: 'color',
  icon: 'icon',
  isInitial: 'isInitial',
  isFinal: 'isFinal',
  isWon: 'isWon',
  isLost: 'isLost',
  allowReopen: 'allowReopen',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type JourneyStateScalarFieldEnum = (typeof JourneyStateScalarFieldEnum)[keyof typeof JourneyStateScalarFieldEnum]


export const CommercialJourneyScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  leadId: 'leadId',
  clientId: 'clientId',
  consultantId: 'consultantId',
  title: 'title',
  consortiumType: 'consortiumType',
  currentPhaseId: 'currentPhaseId',
  currentStateId: 'currentStateId',
  priority: 'priority',
  score: 'score',
  outcome: 'outcome',
  stateEnteredAt: 'stateEnteredAt',
  lastInteractionAt: 'lastInteractionAt',
  closedAt: 'closedAt',
  version: 'version',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommercialJourneyScalarFieldEnum = (typeof CommercialJourneyScalarFieldEnum)[keyof typeof CommercialJourneyScalarFieldEnum]


export const CommercialEventScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  journeyId: 'journeyId',
  type: 'type',
  actorType: 'actorType',
  actorId: 'actorId',
  payload: 'payload',
  occurredAt: 'occurredAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommercialEventScalarFieldEnum = (typeof CommercialEventScalarFieldEnum)[keyof typeof CommercialEventScalarFieldEnum]


export const CommercialActionScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  journeyId: 'journeyId',
  type: 'type',
  status: 'status',
  origin: 'origin',
  actorType: 'actorType',
  actorId: 'actorId',
  title: 'title',
  description: 'description',
  payload: 'payload',
  scheduledFor: 'scheduledFor',
  startedAt: 'startedAt',
  completedAt: 'completedAt',
  failedAt: 'failedAt',
  failureReason: 'failureReason',
  createdBy: 'createdBy',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type CommercialActionScalarFieldEnum = (typeof CommercialActionScalarFieldEnum)[keyof typeof CommercialActionScalarFieldEnum]


export const WorkflowRuleScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  name: 'name',
  description: 'description',
  eventType: 'eventType',
  sourceStateId: 'sourceStateId',
  targetStateId: 'targetStateId',
  conditions: 'conditions',
  actions: 'actions',
  priority: 'priority',
  stopProcessingAfterMatch: 'stopProcessingAfterMatch',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type WorkflowRuleScalarFieldEnum = (typeof WorkflowRuleScalarFieldEnum)[keyof typeof WorkflowRuleScalarFieldEnum]


export const NextBestActionScalarFieldEnum = {
  id: 'id',
  workspaceId: 'workspaceId',
  journeyId: 'journeyId',
  actionType: 'actionType',
  title: 'title',
  description: 'description',
  reason: 'reason',
  confidence: 'confidence',
  priority: 'priority',
  source: 'source',
  expiresAt: 'expiresAt',
  acceptedAt: 'acceptedAt',
  rejectedAt: 'rejectedAt',
  executedActionId: 'executedActionId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type NextBestActionScalarFieldEnum = (typeof NextBestActionScalarFieldEnum)[keyof typeof NextBestActionScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const JsonNullValueInput = {
  JsonNull: JsonNull
} as const

export type JsonNullValueInput = (typeof JsonNullValueInput)[keyof typeof JsonNullValueInput]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]


export const JsonNullValueFilter = {
  DbNull: DbNull,
  JsonNull: JsonNull,
  AnyNull: AnyNull
} as const

export type JsonNullValueFilter = (typeof JsonNullValueFilter)[keyof typeof JsonNullValueFilter]

