
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `CommercialEvent` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model CommercialEvent
 * 
 */
export type CommercialEventModel = runtime.Types.Result.DefaultSelection<Prisma.$CommercialEventPayload>

export type AggregateCommercialEvent = {
  _count: CommercialEventCountAggregateOutputType | null
  _min: CommercialEventMinAggregateOutputType | null
  _max: CommercialEventMaxAggregateOutputType | null
}

export type CommercialEventMinAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  journeyId: string | null
  type: $Enums.CommercialEventType | null
  actorType: $Enums.CommercialActorType | null
  actorId: string | null
  occurredAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CommercialEventMaxAggregateOutputType = {
  id: string | null
  workspaceId: string | null
  journeyId: string | null
  type: $Enums.CommercialEventType | null
  actorType: $Enums.CommercialActorType | null
  actorId: string | null
  occurredAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type CommercialEventCountAggregateOutputType = {
  id: number
  workspaceId: number
  journeyId: number
  type: number
  actorType: number
  actorId: number
  payload: number
  occurredAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type CommercialEventMinAggregateInputType = {
  id?: true
  workspaceId?: true
  journeyId?: true
  type?: true
  actorType?: true
  actorId?: true
  occurredAt?: true
  createdAt?: true
  updatedAt?: true
}

export type CommercialEventMaxAggregateInputType = {
  id?: true
  workspaceId?: true
  journeyId?: true
  type?: true
  actorType?: true
  actorId?: true
  occurredAt?: true
  createdAt?: true
  updatedAt?: true
}

export type CommercialEventCountAggregateInputType = {
  id?: true
  workspaceId?: true
  journeyId?: true
  type?: true
  actorType?: true
  actorId?: true
  payload?: true
  occurredAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type CommercialEventAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CommercialEvent to aggregate.
   */
  where?: Prisma.CommercialEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommercialEvents to fetch.
   */
  orderBy?: Prisma.CommercialEventOrderByWithRelationInput | Prisma.CommercialEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.CommercialEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommercialEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommercialEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned CommercialEvents
  **/
  _count?: true | CommercialEventCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: CommercialEventMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: CommercialEventMaxAggregateInputType
}

export type GetCommercialEventAggregateType<T extends CommercialEventAggregateArgs> = {
      [P in keyof T & keyof AggregateCommercialEvent]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCommercialEvent[P]>
    : Prisma.GetScalarType<T[P], AggregateCommercialEvent[P]>
}




export type CommercialEventGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.CommercialEventWhereInput
  orderBy?: Prisma.CommercialEventOrderByWithAggregationInput | Prisma.CommercialEventOrderByWithAggregationInput[]
  by: Prisma.CommercialEventScalarFieldEnum[] | Prisma.CommercialEventScalarFieldEnum
  having?: Prisma.CommercialEventScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CommercialEventCountAggregateInputType | true
  _min?: CommercialEventMinAggregateInputType
  _max?: CommercialEventMaxAggregateInputType
}

export type CommercialEventGroupByOutputType = {
  id: string
  workspaceId: string
  journeyId: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId: string | null
  payload: runtime.JsonValue
  occurredAt: Date
  createdAt: Date
  updatedAt: Date
  _count: CommercialEventCountAggregateOutputType | null
  _min: CommercialEventMinAggregateOutputType | null
  _max: CommercialEventMaxAggregateOutputType | null
}

export type GetCommercialEventGroupByPayload<T extends CommercialEventGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CommercialEventGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof CommercialEventGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], CommercialEventGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], CommercialEventGroupByOutputType[P]>
      }
    >
  >



export type CommercialEventWhereInput = {
  AND?: Prisma.CommercialEventWhereInput | Prisma.CommercialEventWhereInput[]
  OR?: Prisma.CommercialEventWhereInput[]
  NOT?: Prisma.CommercialEventWhereInput | Prisma.CommercialEventWhereInput[]
  id?: Prisma.StringFilter<"CommercialEvent"> | string
  workspaceId?: Prisma.StringFilter<"CommercialEvent"> | string
  journeyId?: Prisma.StringFilter<"CommercialEvent"> | string
  type?: Prisma.EnumCommercialEventTypeFilter<"CommercialEvent"> | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFilter<"CommercialEvent"> | $Enums.CommercialActorType
  actorId?: Prisma.StringNullableFilter<"CommercialEvent"> | string | null
  payload?: Prisma.JsonFilter<"CommercialEvent">
  occurredAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  journey?: Prisma.XOR<Prisma.CommercialJourneyScalarRelationFilter, Prisma.CommercialJourneyWhereInput>
}

export type CommercialEventOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  actorType?: Prisma.SortOrder
  actorId?: Prisma.SortOrderInput | Prisma.SortOrder
  payload?: Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  workspace?: Prisma.WorkspaceOrderByWithRelationInput
  journey?: Prisma.CommercialJourneyOrderByWithRelationInput
}

export type CommercialEventWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.CommercialEventWhereInput | Prisma.CommercialEventWhereInput[]
  OR?: Prisma.CommercialEventWhereInput[]
  NOT?: Prisma.CommercialEventWhereInput | Prisma.CommercialEventWhereInput[]
  workspaceId?: Prisma.StringFilter<"CommercialEvent"> | string
  journeyId?: Prisma.StringFilter<"CommercialEvent"> | string
  type?: Prisma.EnumCommercialEventTypeFilter<"CommercialEvent"> | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFilter<"CommercialEvent"> | $Enums.CommercialActorType
  actorId?: Prisma.StringNullableFilter<"CommercialEvent"> | string | null
  payload?: Prisma.JsonFilter<"CommercialEvent">
  occurredAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
  workspace?: Prisma.XOR<Prisma.WorkspaceScalarRelationFilter, Prisma.WorkspaceWhereInput>
  journey?: Prisma.XOR<Prisma.CommercialJourneyScalarRelationFilter, Prisma.CommercialJourneyWhereInput>
}, "id">

export type CommercialEventOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  actorType?: Prisma.SortOrder
  actorId?: Prisma.SortOrderInput | Prisma.SortOrder
  payload?: Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.CommercialEventCountOrderByAggregateInput
  _max?: Prisma.CommercialEventMaxOrderByAggregateInput
  _min?: Prisma.CommercialEventMinOrderByAggregateInput
}

export type CommercialEventScalarWhereWithAggregatesInput = {
  AND?: Prisma.CommercialEventScalarWhereWithAggregatesInput | Prisma.CommercialEventScalarWhereWithAggregatesInput[]
  OR?: Prisma.CommercialEventScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CommercialEventScalarWhereWithAggregatesInput | Prisma.CommercialEventScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"CommercialEvent"> | string
  workspaceId?: Prisma.StringWithAggregatesFilter<"CommercialEvent"> | string
  journeyId?: Prisma.StringWithAggregatesFilter<"CommercialEvent"> | string
  type?: Prisma.EnumCommercialEventTypeWithAggregatesFilter<"CommercialEvent"> | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeWithAggregatesFilter<"CommercialEvent"> | $Enums.CommercialActorType
  actorId?: Prisma.StringNullableWithAggregatesFilter<"CommercialEvent"> | string | null
  payload?: Prisma.JsonWithAggregatesFilter<"CommercialEvent">
  occurredAt?: Prisma.DateTimeWithAggregatesFilter<"CommercialEvent"> | Date | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"CommercialEvent"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"CommercialEvent"> | Date | string
}

export type CommercialEventCreateInput = {
  id?: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutCommercialEventsInput
  journey: Prisma.CommercialJourneyCreateNestedOneWithoutCommercialEventsInput
}

export type CommercialEventUncheckedCreateInput = {
  id?: string
  workspaceId: string
  journeyId: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommercialEventUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutCommercialEventsNestedInput
  journey?: Prisma.CommercialJourneyUpdateOneRequiredWithoutCommercialEventsNestedInput
}

export type CommercialEventUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommercialEventCreateManyInput = {
  id?: string
  workspaceId: string
  journeyId: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommercialEventUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommercialEventUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommercialEventListRelationFilter = {
  every?: Prisma.CommercialEventWhereInput
  some?: Prisma.CommercialEventWhereInput
  none?: Prisma.CommercialEventWhereInput
}

export type CommercialEventOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CommercialEventCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  actorType?: Prisma.SortOrder
  actorId?: Prisma.SortOrder
  payload?: Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommercialEventMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  actorType?: Prisma.SortOrder
  actorId?: Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommercialEventMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  workspaceId?: Prisma.SortOrder
  journeyId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  actorType?: Prisma.SortOrder
  actorId?: Prisma.SortOrder
  occurredAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type CommercialEventCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.CommercialEventCreateWithoutWorkspaceInput, Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput> | Prisma.CommercialEventCreateWithoutWorkspaceInput[] | Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.CommercialEventCreateOrConnectWithoutWorkspaceInput | Prisma.CommercialEventCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.CommercialEventCreateManyWorkspaceInputEnvelope
  connect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
}

export type CommercialEventUncheckedCreateNestedManyWithoutWorkspaceInput = {
  create?: Prisma.XOR<Prisma.CommercialEventCreateWithoutWorkspaceInput, Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput> | Prisma.CommercialEventCreateWithoutWorkspaceInput[] | Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.CommercialEventCreateOrConnectWithoutWorkspaceInput | Prisma.CommercialEventCreateOrConnectWithoutWorkspaceInput[]
  createMany?: Prisma.CommercialEventCreateManyWorkspaceInputEnvelope
  connect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
}

export type CommercialEventUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.CommercialEventCreateWithoutWorkspaceInput, Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput> | Prisma.CommercialEventCreateWithoutWorkspaceInput[] | Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.CommercialEventCreateOrConnectWithoutWorkspaceInput | Prisma.CommercialEventCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.CommercialEventUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.CommercialEventUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.CommercialEventCreateManyWorkspaceInputEnvelope
  set?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  disconnect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  delete?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  connect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  update?: Prisma.CommercialEventUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.CommercialEventUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.CommercialEventUpdateManyWithWhereWithoutWorkspaceInput | Prisma.CommercialEventUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.CommercialEventScalarWhereInput | Prisma.CommercialEventScalarWhereInput[]
}

export type CommercialEventUncheckedUpdateManyWithoutWorkspaceNestedInput = {
  create?: Prisma.XOR<Prisma.CommercialEventCreateWithoutWorkspaceInput, Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput> | Prisma.CommercialEventCreateWithoutWorkspaceInput[] | Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput[]
  connectOrCreate?: Prisma.CommercialEventCreateOrConnectWithoutWorkspaceInput | Prisma.CommercialEventCreateOrConnectWithoutWorkspaceInput[]
  upsert?: Prisma.CommercialEventUpsertWithWhereUniqueWithoutWorkspaceInput | Prisma.CommercialEventUpsertWithWhereUniqueWithoutWorkspaceInput[]
  createMany?: Prisma.CommercialEventCreateManyWorkspaceInputEnvelope
  set?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  disconnect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  delete?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  connect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  update?: Prisma.CommercialEventUpdateWithWhereUniqueWithoutWorkspaceInput | Prisma.CommercialEventUpdateWithWhereUniqueWithoutWorkspaceInput[]
  updateMany?: Prisma.CommercialEventUpdateManyWithWhereWithoutWorkspaceInput | Prisma.CommercialEventUpdateManyWithWhereWithoutWorkspaceInput[]
  deleteMany?: Prisma.CommercialEventScalarWhereInput | Prisma.CommercialEventScalarWhereInput[]
}

export type CommercialEventCreateNestedManyWithoutJourneyInput = {
  create?: Prisma.XOR<Prisma.CommercialEventCreateWithoutJourneyInput, Prisma.CommercialEventUncheckedCreateWithoutJourneyInput> | Prisma.CommercialEventCreateWithoutJourneyInput[] | Prisma.CommercialEventUncheckedCreateWithoutJourneyInput[]
  connectOrCreate?: Prisma.CommercialEventCreateOrConnectWithoutJourneyInput | Prisma.CommercialEventCreateOrConnectWithoutJourneyInput[]
  createMany?: Prisma.CommercialEventCreateManyJourneyInputEnvelope
  connect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
}

export type CommercialEventUncheckedCreateNestedManyWithoutJourneyInput = {
  create?: Prisma.XOR<Prisma.CommercialEventCreateWithoutJourneyInput, Prisma.CommercialEventUncheckedCreateWithoutJourneyInput> | Prisma.CommercialEventCreateWithoutJourneyInput[] | Prisma.CommercialEventUncheckedCreateWithoutJourneyInput[]
  connectOrCreate?: Prisma.CommercialEventCreateOrConnectWithoutJourneyInput | Prisma.CommercialEventCreateOrConnectWithoutJourneyInput[]
  createMany?: Prisma.CommercialEventCreateManyJourneyInputEnvelope
  connect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
}

export type CommercialEventUpdateManyWithoutJourneyNestedInput = {
  create?: Prisma.XOR<Prisma.CommercialEventCreateWithoutJourneyInput, Prisma.CommercialEventUncheckedCreateWithoutJourneyInput> | Prisma.CommercialEventCreateWithoutJourneyInput[] | Prisma.CommercialEventUncheckedCreateWithoutJourneyInput[]
  connectOrCreate?: Prisma.CommercialEventCreateOrConnectWithoutJourneyInput | Prisma.CommercialEventCreateOrConnectWithoutJourneyInput[]
  upsert?: Prisma.CommercialEventUpsertWithWhereUniqueWithoutJourneyInput | Prisma.CommercialEventUpsertWithWhereUniqueWithoutJourneyInput[]
  createMany?: Prisma.CommercialEventCreateManyJourneyInputEnvelope
  set?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  disconnect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  delete?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  connect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  update?: Prisma.CommercialEventUpdateWithWhereUniqueWithoutJourneyInput | Prisma.CommercialEventUpdateWithWhereUniqueWithoutJourneyInput[]
  updateMany?: Prisma.CommercialEventUpdateManyWithWhereWithoutJourneyInput | Prisma.CommercialEventUpdateManyWithWhereWithoutJourneyInput[]
  deleteMany?: Prisma.CommercialEventScalarWhereInput | Prisma.CommercialEventScalarWhereInput[]
}

export type CommercialEventUncheckedUpdateManyWithoutJourneyNestedInput = {
  create?: Prisma.XOR<Prisma.CommercialEventCreateWithoutJourneyInput, Prisma.CommercialEventUncheckedCreateWithoutJourneyInput> | Prisma.CommercialEventCreateWithoutJourneyInput[] | Prisma.CommercialEventUncheckedCreateWithoutJourneyInput[]
  connectOrCreate?: Prisma.CommercialEventCreateOrConnectWithoutJourneyInput | Prisma.CommercialEventCreateOrConnectWithoutJourneyInput[]
  upsert?: Prisma.CommercialEventUpsertWithWhereUniqueWithoutJourneyInput | Prisma.CommercialEventUpsertWithWhereUniqueWithoutJourneyInput[]
  createMany?: Prisma.CommercialEventCreateManyJourneyInputEnvelope
  set?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  disconnect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  delete?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  connect?: Prisma.CommercialEventWhereUniqueInput | Prisma.CommercialEventWhereUniqueInput[]
  update?: Prisma.CommercialEventUpdateWithWhereUniqueWithoutJourneyInput | Prisma.CommercialEventUpdateWithWhereUniqueWithoutJourneyInput[]
  updateMany?: Prisma.CommercialEventUpdateManyWithWhereWithoutJourneyInput | Prisma.CommercialEventUpdateManyWithWhereWithoutJourneyInput[]
  deleteMany?: Prisma.CommercialEventScalarWhereInput | Prisma.CommercialEventScalarWhereInput[]
}

export type EnumCommercialEventTypeFieldUpdateOperationsInput = {
  set?: $Enums.CommercialEventType
}

export type EnumCommercialActorTypeFieldUpdateOperationsInput = {
  set?: $Enums.CommercialActorType
}

export type CommercialEventCreateWithoutWorkspaceInput = {
  id?: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  journey: Prisma.CommercialJourneyCreateNestedOneWithoutCommercialEventsInput
}

export type CommercialEventUncheckedCreateWithoutWorkspaceInput = {
  id?: string
  journeyId: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommercialEventCreateOrConnectWithoutWorkspaceInput = {
  where: Prisma.CommercialEventWhereUniqueInput
  create: Prisma.XOR<Prisma.CommercialEventCreateWithoutWorkspaceInput, Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput>
}

export type CommercialEventCreateManyWorkspaceInputEnvelope = {
  data: Prisma.CommercialEventCreateManyWorkspaceInput | Prisma.CommercialEventCreateManyWorkspaceInput[]
  skipDuplicates?: boolean
}

export type CommercialEventUpsertWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.CommercialEventWhereUniqueInput
  update: Prisma.XOR<Prisma.CommercialEventUpdateWithoutWorkspaceInput, Prisma.CommercialEventUncheckedUpdateWithoutWorkspaceInput>
  create: Prisma.XOR<Prisma.CommercialEventCreateWithoutWorkspaceInput, Prisma.CommercialEventUncheckedCreateWithoutWorkspaceInput>
}

export type CommercialEventUpdateWithWhereUniqueWithoutWorkspaceInput = {
  where: Prisma.CommercialEventWhereUniqueInput
  data: Prisma.XOR<Prisma.CommercialEventUpdateWithoutWorkspaceInput, Prisma.CommercialEventUncheckedUpdateWithoutWorkspaceInput>
}

export type CommercialEventUpdateManyWithWhereWithoutWorkspaceInput = {
  where: Prisma.CommercialEventScalarWhereInput
  data: Prisma.XOR<Prisma.CommercialEventUpdateManyMutationInput, Prisma.CommercialEventUncheckedUpdateManyWithoutWorkspaceInput>
}

export type CommercialEventScalarWhereInput = {
  AND?: Prisma.CommercialEventScalarWhereInput | Prisma.CommercialEventScalarWhereInput[]
  OR?: Prisma.CommercialEventScalarWhereInput[]
  NOT?: Prisma.CommercialEventScalarWhereInput | Prisma.CommercialEventScalarWhereInput[]
  id?: Prisma.StringFilter<"CommercialEvent"> | string
  workspaceId?: Prisma.StringFilter<"CommercialEvent"> | string
  journeyId?: Prisma.StringFilter<"CommercialEvent"> | string
  type?: Prisma.EnumCommercialEventTypeFilter<"CommercialEvent"> | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFilter<"CommercialEvent"> | $Enums.CommercialActorType
  actorId?: Prisma.StringNullableFilter<"CommercialEvent"> | string | null
  payload?: Prisma.JsonFilter<"CommercialEvent">
  occurredAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
  createdAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"CommercialEvent"> | Date | string
}

export type CommercialEventCreateWithoutJourneyInput = {
  id?: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
  workspace: Prisma.WorkspaceCreateNestedOneWithoutCommercialEventsInput
}

export type CommercialEventUncheckedCreateWithoutJourneyInput = {
  id?: string
  workspaceId: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommercialEventCreateOrConnectWithoutJourneyInput = {
  where: Prisma.CommercialEventWhereUniqueInput
  create: Prisma.XOR<Prisma.CommercialEventCreateWithoutJourneyInput, Prisma.CommercialEventUncheckedCreateWithoutJourneyInput>
}

export type CommercialEventCreateManyJourneyInputEnvelope = {
  data: Prisma.CommercialEventCreateManyJourneyInput | Prisma.CommercialEventCreateManyJourneyInput[]
  skipDuplicates?: boolean
}

export type CommercialEventUpsertWithWhereUniqueWithoutJourneyInput = {
  where: Prisma.CommercialEventWhereUniqueInput
  update: Prisma.XOR<Prisma.CommercialEventUpdateWithoutJourneyInput, Prisma.CommercialEventUncheckedUpdateWithoutJourneyInput>
  create: Prisma.XOR<Prisma.CommercialEventCreateWithoutJourneyInput, Prisma.CommercialEventUncheckedCreateWithoutJourneyInput>
}

export type CommercialEventUpdateWithWhereUniqueWithoutJourneyInput = {
  where: Prisma.CommercialEventWhereUniqueInput
  data: Prisma.XOR<Prisma.CommercialEventUpdateWithoutJourneyInput, Prisma.CommercialEventUncheckedUpdateWithoutJourneyInput>
}

export type CommercialEventUpdateManyWithWhereWithoutJourneyInput = {
  where: Prisma.CommercialEventScalarWhereInput
  data: Prisma.XOR<Prisma.CommercialEventUpdateManyMutationInput, Prisma.CommercialEventUncheckedUpdateManyWithoutJourneyInput>
}

export type CommercialEventCreateManyWorkspaceInput = {
  id?: string
  journeyId: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommercialEventUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  journey?: Prisma.CommercialJourneyUpdateOneRequiredWithoutCommercialEventsNestedInput
}

export type CommercialEventUncheckedUpdateWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommercialEventUncheckedUpdateManyWithoutWorkspaceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  journeyId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommercialEventCreateManyJourneyInput = {
  id?: string
  workspaceId: string
  type: $Enums.CommercialEventType
  actorType: $Enums.CommercialActorType
  actorId?: string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt: Date | string
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type CommercialEventUpdateWithoutJourneyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  workspace?: Prisma.WorkspaceUpdateOneRequiredWithoutCommercialEventsNestedInput
}

export type CommercialEventUncheckedUpdateWithoutJourneyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type CommercialEventUncheckedUpdateManyWithoutJourneyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  workspaceId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCommercialEventTypeFieldUpdateOperationsInput | $Enums.CommercialEventType
  actorType?: Prisma.EnumCommercialActorTypeFieldUpdateOperationsInput | $Enums.CommercialActorType
  actorId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  payload?: Prisma.JsonNullValueInput | runtime.InputJsonValue
  occurredAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type CommercialEventSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  journeyId?: boolean
  type?: boolean
  actorType?: boolean
  actorId?: boolean
  payload?: boolean
  occurredAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["commercialEvent"]>

export type CommercialEventSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  journeyId?: boolean
  type?: boolean
  actorType?: boolean
  actorId?: boolean
  payload?: boolean
  occurredAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["commercialEvent"]>

export type CommercialEventSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  workspaceId?: boolean
  journeyId?: boolean
  type?: boolean
  actorType?: boolean
  actorId?: boolean
  payload?: boolean
  occurredAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
}, ExtArgs["result"]["commercialEvent"]>

export type CommercialEventSelectScalar = {
  id?: boolean
  workspaceId?: boolean
  journeyId?: boolean
  type?: boolean
  actorType?: boolean
  actorId?: boolean
  payload?: boolean
  occurredAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type CommercialEventOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "workspaceId" | "journeyId" | "type" | "actorType" | "actorId" | "payload" | "occurredAt" | "createdAt" | "updatedAt", ExtArgs["result"]["commercialEvent"]>
export type CommercialEventInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
}
export type CommercialEventIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
}
export type CommercialEventIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  workspace?: boolean | Prisma.WorkspaceDefaultArgs<ExtArgs>
  journey?: boolean | Prisma.CommercialJourneyDefaultArgs<ExtArgs>
}

export type $CommercialEventPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "CommercialEvent"
  objects: {
    workspace: Prisma.$WorkspacePayload<ExtArgs>
    journey: Prisma.$CommercialJourneyPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    workspaceId: string
    journeyId: string
    type: $Enums.CommercialEventType
    actorType: $Enums.CommercialActorType
    actorId: string | null
    payload: runtime.JsonValue
    occurredAt: Date
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["commercialEvent"]>
  composites: {}
}

export type CommercialEventGetPayload<S extends boolean | null | undefined | CommercialEventDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload, S>

export type CommercialEventCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<CommercialEventFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: CommercialEventCountAggregateInputType | true
  }

export interface CommercialEventDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CommercialEvent'], meta: { name: 'CommercialEvent' } }
  /**
   * Find zero or one CommercialEvent that matches the filter.
   * @param {CommercialEventFindUniqueArgs} args - Arguments to find a CommercialEvent
   * @example
   * // Get one CommercialEvent
   * const commercialEvent = await prisma.commercialEvent.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CommercialEventFindUniqueArgs>(args: Prisma.SelectSubset<T, CommercialEventFindUniqueArgs<ExtArgs>>): Prisma.Prisma__CommercialEventClient<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one CommercialEvent that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CommercialEventFindUniqueOrThrowArgs} args - Arguments to find a CommercialEvent
   * @example
   * // Get one CommercialEvent
   * const commercialEvent = await prisma.commercialEvent.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CommercialEventFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, CommercialEventFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommercialEventClient<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CommercialEvent that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommercialEventFindFirstArgs} args - Arguments to find a CommercialEvent
   * @example
   * // Get one CommercialEvent
   * const commercialEvent = await prisma.commercialEvent.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CommercialEventFindFirstArgs>(args?: Prisma.SelectSubset<T, CommercialEventFindFirstArgs<ExtArgs>>): Prisma.Prisma__CommercialEventClient<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first CommercialEvent that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommercialEventFindFirstOrThrowArgs} args - Arguments to find a CommercialEvent
   * @example
   * // Get one CommercialEvent
   * const commercialEvent = await prisma.commercialEvent.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CommercialEventFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, CommercialEventFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__CommercialEventClient<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more CommercialEvents that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommercialEventFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CommercialEvents
   * const commercialEvents = await prisma.commercialEvent.findMany()
   * 
   * // Get first 10 CommercialEvents
   * const commercialEvents = await prisma.commercialEvent.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const commercialEventWithIdOnly = await prisma.commercialEvent.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends CommercialEventFindManyArgs>(args?: Prisma.SelectSubset<T, CommercialEventFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a CommercialEvent.
   * @param {CommercialEventCreateArgs} args - Arguments to create a CommercialEvent.
   * @example
   * // Create one CommercialEvent
   * const CommercialEvent = await prisma.commercialEvent.create({
   *   data: {
   *     // ... data to create a CommercialEvent
   *   }
   * })
   * 
   */
  create<T extends CommercialEventCreateArgs>(args: Prisma.SelectSubset<T, CommercialEventCreateArgs<ExtArgs>>): Prisma.Prisma__CommercialEventClient<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many CommercialEvents.
   * @param {CommercialEventCreateManyArgs} args - Arguments to create many CommercialEvents.
   * @example
   * // Create many CommercialEvents
   * const commercialEvent = await prisma.commercialEvent.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends CommercialEventCreateManyArgs>(args?: Prisma.SelectSubset<T, CommercialEventCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CommercialEvents and returns the data saved in the database.
   * @param {CommercialEventCreateManyAndReturnArgs} args - Arguments to create many CommercialEvents.
   * @example
   * // Create many CommercialEvents
   * const commercialEvent = await prisma.commercialEvent.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many CommercialEvents and only return the `id`
   * const commercialEventWithIdOnly = await prisma.commercialEvent.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends CommercialEventCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, CommercialEventCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a CommercialEvent.
   * @param {CommercialEventDeleteArgs} args - Arguments to delete one CommercialEvent.
   * @example
   * // Delete one CommercialEvent
   * const CommercialEvent = await prisma.commercialEvent.delete({
   *   where: {
   *     // ... filter to delete one CommercialEvent
   *   }
   * })
   * 
   */
  delete<T extends CommercialEventDeleteArgs>(args: Prisma.SelectSubset<T, CommercialEventDeleteArgs<ExtArgs>>): Prisma.Prisma__CommercialEventClient<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one CommercialEvent.
   * @param {CommercialEventUpdateArgs} args - Arguments to update one CommercialEvent.
   * @example
   * // Update one CommercialEvent
   * const commercialEvent = await prisma.commercialEvent.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends CommercialEventUpdateArgs>(args: Prisma.SelectSubset<T, CommercialEventUpdateArgs<ExtArgs>>): Prisma.Prisma__CommercialEventClient<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more CommercialEvents.
   * @param {CommercialEventDeleteManyArgs} args - Arguments to filter CommercialEvents to delete.
   * @example
   * // Delete a few CommercialEvents
   * const { count } = await prisma.commercialEvent.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends CommercialEventDeleteManyArgs>(args?: Prisma.SelectSubset<T, CommercialEventDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CommercialEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommercialEventUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CommercialEvents
   * const commercialEvent = await prisma.commercialEvent.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends CommercialEventUpdateManyArgs>(args: Prisma.SelectSubset<T, CommercialEventUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CommercialEvents and returns the data updated in the database.
   * @param {CommercialEventUpdateManyAndReturnArgs} args - Arguments to update many CommercialEvents.
   * @example
   * // Update many CommercialEvents
   * const commercialEvent = await prisma.commercialEvent.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more CommercialEvents and only return the `id`
   * const commercialEventWithIdOnly = await prisma.commercialEvent.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends CommercialEventUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, CommercialEventUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one CommercialEvent.
   * @param {CommercialEventUpsertArgs} args - Arguments to update or create a CommercialEvent.
   * @example
   * // Update or create a CommercialEvent
   * const commercialEvent = await prisma.commercialEvent.upsert({
   *   create: {
   *     // ... data to create a CommercialEvent
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CommercialEvent we want to update
   *   }
   * })
   */
  upsert<T extends CommercialEventUpsertArgs>(args: Prisma.SelectSubset<T, CommercialEventUpsertArgs<ExtArgs>>): Prisma.Prisma__CommercialEventClient<runtime.Types.Result.GetResult<Prisma.$CommercialEventPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of CommercialEvents.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommercialEventCountArgs} args - Arguments to filter CommercialEvents to count.
   * @example
   * // Count the number of CommercialEvents
   * const count = await prisma.commercialEvent.count({
   *   where: {
   *     // ... the filter for the CommercialEvents we want to count
   *   }
   * })
  **/
  count<T extends CommercialEventCountArgs>(
    args?: Prisma.Subset<T, CommercialEventCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CommercialEventCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CommercialEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommercialEventAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends CommercialEventAggregateArgs>(args: Prisma.Subset<T, CommercialEventAggregateArgs>): Prisma.PrismaPromise<GetCommercialEventAggregateType<T>>

  /**
   * Group by CommercialEvent.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CommercialEventGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends CommercialEventGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CommercialEventGroupByArgs['orderBy'] }
      : { orderBy?: CommercialEventGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, CommercialEventGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetCommercialEventGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the CommercialEvent model
 */
readonly fields: CommercialEventFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for CommercialEvent.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CommercialEventClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  workspace<T extends Prisma.WorkspaceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.WorkspaceDefaultArgs<ExtArgs>>): Prisma.Prisma__WorkspaceClient<runtime.Types.Result.GetResult<Prisma.$WorkspacePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  journey<T extends Prisma.CommercialJourneyDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.CommercialJourneyDefaultArgs<ExtArgs>>): Prisma.Prisma__CommercialJourneyClient<runtime.Types.Result.GetResult<Prisma.$CommercialJourneyPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the CommercialEvent model
 */
export interface CommercialEventFieldRefs {
  readonly id: Prisma.FieldRef<"CommercialEvent", 'String'>
  readonly workspaceId: Prisma.FieldRef<"CommercialEvent", 'String'>
  readonly journeyId: Prisma.FieldRef<"CommercialEvent", 'String'>
  readonly type: Prisma.FieldRef<"CommercialEvent", 'CommercialEventType'>
  readonly actorType: Prisma.FieldRef<"CommercialEvent", 'CommercialActorType'>
  readonly actorId: Prisma.FieldRef<"CommercialEvent", 'String'>
  readonly payload: Prisma.FieldRef<"CommercialEvent", 'Json'>
  readonly occurredAt: Prisma.FieldRef<"CommercialEvent", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"CommercialEvent", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"CommercialEvent", 'DateTime'>
}
    

// Custom InputTypes
/**
 * CommercialEvent findUnique
 */
export type CommercialEventFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * Filter, which CommercialEvent to fetch.
   */
  where: Prisma.CommercialEventWhereUniqueInput
}

/**
 * CommercialEvent findUniqueOrThrow
 */
export type CommercialEventFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * Filter, which CommercialEvent to fetch.
   */
  where: Prisma.CommercialEventWhereUniqueInput
}

/**
 * CommercialEvent findFirst
 */
export type CommercialEventFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * Filter, which CommercialEvent to fetch.
   */
  where?: Prisma.CommercialEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommercialEvents to fetch.
   */
  orderBy?: Prisma.CommercialEventOrderByWithRelationInput | Prisma.CommercialEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CommercialEvents.
   */
  cursor?: Prisma.CommercialEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommercialEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommercialEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommercialEvents.
   */
  distinct?: Prisma.CommercialEventScalarFieldEnum | Prisma.CommercialEventScalarFieldEnum[]
}

/**
 * CommercialEvent findFirstOrThrow
 */
export type CommercialEventFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * Filter, which CommercialEvent to fetch.
   */
  where?: Prisma.CommercialEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommercialEvents to fetch.
   */
  orderBy?: Prisma.CommercialEventOrderByWithRelationInput | Prisma.CommercialEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for CommercialEvents.
   */
  cursor?: Prisma.CommercialEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommercialEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommercialEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommercialEvents.
   */
  distinct?: Prisma.CommercialEventScalarFieldEnum | Prisma.CommercialEventScalarFieldEnum[]
}

/**
 * CommercialEvent findMany
 */
export type CommercialEventFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * Filter, which CommercialEvents to fetch.
   */
  where?: Prisma.CommercialEventWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of CommercialEvents to fetch.
   */
  orderBy?: Prisma.CommercialEventOrderByWithRelationInput | Prisma.CommercialEventOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing CommercialEvents.
   */
  cursor?: Prisma.CommercialEventWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` CommercialEvents from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` CommercialEvents.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of CommercialEvents.
   */
  distinct?: Prisma.CommercialEventScalarFieldEnum | Prisma.CommercialEventScalarFieldEnum[]
}

/**
 * CommercialEvent create
 */
export type CommercialEventCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * The data needed to create a CommercialEvent.
   */
  data: Prisma.XOR<Prisma.CommercialEventCreateInput, Prisma.CommercialEventUncheckedCreateInput>
}

/**
 * CommercialEvent createMany
 */
export type CommercialEventCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many CommercialEvents.
   */
  data: Prisma.CommercialEventCreateManyInput | Prisma.CommercialEventCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CommercialEvent createManyAndReturn
 */
export type CommercialEventCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * The data used to create many CommercialEvents.
   */
  data: Prisma.CommercialEventCreateManyInput | Prisma.CommercialEventCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CommercialEvent update
 */
export type CommercialEventUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * The data needed to update a CommercialEvent.
   */
  data: Prisma.XOR<Prisma.CommercialEventUpdateInput, Prisma.CommercialEventUncheckedUpdateInput>
  /**
   * Choose, which CommercialEvent to update.
   */
  where: Prisma.CommercialEventWhereUniqueInput
}

/**
 * CommercialEvent updateMany
 */
export type CommercialEventUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update CommercialEvents.
   */
  data: Prisma.XOR<Prisma.CommercialEventUpdateManyMutationInput, Prisma.CommercialEventUncheckedUpdateManyInput>
  /**
   * Filter which CommercialEvents to update
   */
  where?: Prisma.CommercialEventWhereInput
  /**
   * Limit how many CommercialEvents to update.
   */
  limit?: number
}

/**
 * CommercialEvent updateManyAndReturn
 */
export type CommercialEventUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * The data used to update CommercialEvents.
   */
  data: Prisma.XOR<Prisma.CommercialEventUpdateManyMutationInput, Prisma.CommercialEventUncheckedUpdateManyInput>
  /**
   * Filter which CommercialEvents to update
   */
  where?: Prisma.CommercialEventWhereInput
  /**
   * Limit how many CommercialEvents to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CommercialEvent upsert
 */
export type CommercialEventUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * The filter to search for the CommercialEvent to update in case it exists.
   */
  where: Prisma.CommercialEventWhereUniqueInput
  /**
   * In case the CommercialEvent found by the `where` argument doesn't exist, create a new CommercialEvent with this data.
   */
  create: Prisma.XOR<Prisma.CommercialEventCreateInput, Prisma.CommercialEventUncheckedCreateInput>
  /**
   * In case the CommercialEvent was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CommercialEventUpdateInput, Prisma.CommercialEventUncheckedUpdateInput>
}

/**
 * CommercialEvent delete
 */
export type CommercialEventDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
  /**
   * Filter which CommercialEvent to delete.
   */
  where: Prisma.CommercialEventWhereUniqueInput
}

/**
 * CommercialEvent deleteMany
 */
export type CommercialEventDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which CommercialEvents to delete
   */
  where?: Prisma.CommercialEventWhereInput
  /**
   * Limit how many CommercialEvents to delete.
   */
  limit?: number
}

/**
 * CommercialEvent without action
 */
export type CommercialEventDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the CommercialEvent
   */
  select?: Prisma.CommercialEventSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CommercialEvent
   */
  omit?: Prisma.CommercialEventOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CommercialEventInclude<ExtArgs> | null
}
